function Menu(mamenu, ten) {
    this.mamenu = mamenu;
    this.ten = ten;
}
var m = new Array();
m[0] = new Menu("HD", "Hành động");
m[1] = new Menu("NV", "Nhập vai");
m[2] = new Menu("GL", "Giả lập");
m[3] = new Menu("VT", "Viễn tưởng");
m[4] = new Menu("ID", "Indie");
m[5] = new Menu("PL", "Phiêu lưu");
m[6] = new Menu("KD", "Kinh dị");
m[7] = new Menu("TT", "Thể thao");
m[8] = new Menu("ST", "Sinh tồn");
m[9] = new Menu("FPS", "FPS");
m[10] = new Menu("TGM", "Thế giới mở");
m[11] = new Menu("CT", "Chiến thuật");
function sanpham(masp,mamenu,tengame,gia,hinh,noidung)
{
	this.masp=masp;
	this.mamenu=mamenu;
	this.tengame=tengame;
	this.gia=gia;
	this.hinh=hinh;
	this.noidung=noidung;
}
var sp = new Array();
sp[0] = new sanpham("0","HD FPS CT","Counter Strike: Global Offense","140.000","./img/content/csgo/csgo-0.jpg","Giới thiệu về game:</br></br>- Counter-Strike: Global Offensive (viết tắt là CS:GO) là một trò chơi máy tính thuộc thể loại bắn súng góc nhìn thứ nhất và chiến thuật trực tuyến được phát triển bởi Valve Corporation và Hidden Path Entertainment, đơn vị cũng đã duy trì Counter-Strike: Source sau khi phát hành. Đây là bản thứ tư và cũng là bản mới nhất trong dòng game nổi tiếng Counter-Strike.</br></br>Cấu hình tối thiểu:</br></br>Bộ xử lí Chip I3 thế hệ 4 trở lên</br>Bộ nhớ trong: Ram 4g</br>Card rời tối thiểu 2g thế hệ mới.</br>DirectX: Version 11</br>Network: Broadband Internet connection.</br>Ổ Cứng 250 hoặc ssd 220</br>Tốc độ mạng sử dụng 27m – 45m </br></br>Xin liên hệ hotline: 1900-8888 để được hỗ trợ tốt nhất.");
sp[1] = new sanpham("1","HD ST CT","PLAYERUNKNOWN'S BATTLEGROUNDS","340.000","./img/content/pubg/pubg-0.jpg","Giới thiệu về game:</br></br>-PUBG là từ viết tắt của PlayerUnknown’s Battlegrounds, một thể loại game thuộc dạng đấu trường sinh tử. Nội dung của game là 100 người chơi sẽ bị thả xuống một hòn đảo có diện tích 18×18 km, tại đây tất cả mọi người phải tự tìm kiếm vũ khí, phương tiện và những trang thiết bị cần thiết cho mình để chiến đấu với kẻ thù cho tới chết. Để giành kéo dài thời gian sinh tồn và giành chiến thắng đòi hỏi người chơi phải tận dụng tất cả mọi kỹ năng mà mình có, từ sinh tồn, ẩn nấp, ám sát cho đến chiến đấu để có thể là người sống sót duy nhất trên đảo.</br></br>Cấu hình tối thiểu:</br></br>Bộ xử lí Chip I3 thế hệ 4 trở lên</br>Bộ nhớ trong: Ram 4g</br>Card rời tối thiểu 2g thế hệ mới.</br>DirectX: Version 11</br>Network: Broadband Internet connection.</br>Ổ Cứng 250 hoặc ssd 220</br>Tốc độ mạng sử dụng 27m – 45m </br></br>Xin liên hệ hotline: 1900-8888 để được hỗ trợ tốt nhất.");
sp[2] = new sanpham("2","HD NV TGM","Grand Theft Auto V","380.000","./img/content/gtav/gtav-0.jpg","Giới thiệu về game:</br></br>-Grand Theft Auto V là game thực tế ảo trong đó người chơi sẽ nhập vai một trong ba nhân vật có trong game để hoàn thành nhiệm vụ, tấc nhiên là ba người thì mỗi người có một tính cách khác nhau.</br></br>Cấu hình tối thiểu:</br></br>Bộ xử lí Chip I3 thế hệ 4 trở lên</br>Bộ nhớ trong: Ram 4g</br>Card rời tối thiểu 2g thế hệ mới.</br>DirectX: Version 11</br>Network: Broadband Internet connection.</br>Ổ Cứng 250 hoặc ssd 220</br>Tốc độ mạng sử dụng 27m – 45m </br></br>Xin liên hệ hotline: 1900-8888 để được hỗ trợ tốt nhất. ");
sp[3] = new sanpham("3","NV PL","MONSTER HUNTER: WORLD","739.000","./img/content/mhw/mhw-0.jpg","Giới thiệu về game:</br></br>-Ngay từ tiêu đề : bạn sẽ săn quái vật. Monster Hunter: World là game nhập vai hành động dưới góc nhìn người thứ ba. Bạn sẽ chiến đấu với những con quái vật khổng lồ và hoàn thành các nhiệm vụ được giao. Bạn sẽ hợp tác với bạn bè thành một tổ đội “ngon lành” và đi săn. Bạn chỉ cần giết một con quái vật, lấy xương cốt vật liệu, sử dụng những vật liệu đó để chế tạo dụng cụ mới, sau đó giết một con quái vật lớn hơn. Hoặc giết con quái vật đó một lần nữa, nhưng cấp độ mạnh hơn. Bạn cũng có thể bắt được quái vật để có được nhiều tài nguyên hơn từ chúng.</br></br>Cấu hình thối thiểu:</br></br>Bộ xử lí Chip I3 thế hệ 4 trở lên</br>Bộ nhớ trong: Ram 4g</br>Card rời tối thiểu 2g thế hệ mới.</br>DirectX: Version 11</br>Network: Broadband Internet connection.</br>Ổ Cứng 250 hoặc ssd 220</br>Tốc độ mạng sử dụng 27m – 45m </br></br>Xin liên hệ hotline: 1900-8888 để được hỗ trợ tốt nhất.");
sp[4] = new sanpham("4","NV TGM FPS","Far Cry 5 - Standard Edition","914.000","./img/content/fc5/fc5-0.jpg","Giới thiệu về game:</br></br>-Trò chơi diễn ra ở Hạt Hope, một vùng hư cấu của Montana , Hoa Kỳ. Câu chuyện chính xoay quanh Dự án tại Eden's Gate, một sự thờ phượng ngày tận thế quy định vùng đất dưới vỏ bọc của nhà lãnh đạo lôi cuốn của nó, Joseph Seed. Người chơi điều khiển một cảnh sát trưởng chưa được đặt tên là người bị mắc kẹt ở Hope County, và phải làm việc cùng với các phe phái của một kháng chiến để giải phóng hạt khỏi sự cai trị khinh thường của Hạt giống và Cánh cổng Eden. Gameplay tập trung vào chiến đấu và thăm dò; người chơi chiến đấu với quân địch và động vật hoang dã nguy hiểm bằng cách sử dụng một loạt các vũ khí. Trò chơi có nhiều yếu tố được tìm thấy trong các trò chơi nhập vai, chẳng hạn như cốt truyện phân nhánh và nhiệm vụ phụ. Trò chơi cũng có trình chỉnh sửa bản đồ, chế độ nhiều người chơi hợp tác và chế độ nhiều người chơi cạnh tranh.</br></br>Cấu hình tối thiểu:</br></br>Bộ xử lí Chip I3 thế hệ 4 trở lên</br>Bộ nhớ trong: Ram 4g</br>Card rời tối thiểu 2g thế hệ mới.</br>DirectX: Version 11</br>Network: Broadband Internet connection.</br>Ổ Cứng 250 hoặc ssd 220</br>Tốc độ mạng sử dụng 27m – 45m </br></br>Xin liên hệ hotline: 1900-8888 để được hỗ trợ tốt nhất.");
sp[5] = new sanpham("5","HD NV PL","Shadow of the Tomb Raider","1.291.500","./img/content/sottr/sottr-0.jpg","Giới thiệu về game:</br></br>-Shadow of the Tomb Raider là một game phiêu lưu hành động được chơi từ góc nhìn người thứ ba; người chơi điều khiển nhân vật chính Lara Croft khi cô khám phá các địa hình trên khắp lục địa Nam Mỹ. Trung tâm của trò chơi được coi là lớn nhất trong cả loạt và cũng tiết lộ thành phố Paititi bí ẩn. Người chơi có thể tham gia vào các nhiệm vụ chính, phụ và tìm hiểu về Paititi, mang lại trải nghiệm phong phú hơn. Một hệ thống đổi hàng mới cho phép người chơi trao đổi vật phẩm, các bộ phận cấp cứu và vũ khí ở Paititi[3][4] . Có nhiều điều chỉnh được thực hiện cho trò chơi, không giống với Rise. Cách điều khiển khi bơi đã được sửa đổi hoàn toàn, vì Lara giờ đây có thể giữ hơi thở của mình dưới nước trong một khoảng thời gian nhờ sự ra đời của túi khí. Cô cũng có khả năng trèo xuống một vách đá bằng cách sử dụng dây thừng. Lén lút trở thành một phần quan trọng của trò chơi, Lara có thể không chiến đấu khi cô thoát khỏi tầm nhìn của kẻ địch bằng cách che phủ mình trong bùn, trốn trong bụi cây hoặc dựa tường.</br></br>Cấu hình tối thiểu:</br></br>Bộ xử lí Chip I3 thế hệ 4 trở lên</br>Bộ nhớ trong: Ram 4g</br>Card rời tối thiểu 2g thế hệ mới.</br>DirectX: Version 11</br>Network: Broadband Internet connection.</br>Ổ Cứng 250 hoặc ssd 220</br>Tốc độ mạng sử dụng 27m – 45m </br></br>Xin liên hệ hotline: 1900-8888 để được hỗ trợ tốt nhất");
sp[6] = new sanpham("6","HD NV PL TGM","NieR:Automata™","1.250.000","./img/content/nier/nier-0.jpg","Giới thiệu về game:</br></br>-NieR: Automata là một phần tiếp theo của trò NieR, một ngoại truyện của dòng game Drakengard . Bối cảnh ở giữa một cuộc chiến tranh giữa các phe phái máy móc với nhau, được tạo ra bởi kẻ xâm lược ngoài hành tinh và tàn dư của nhân loại. Câu truyện về cuộc chiến của một Android chiến đấu biệt danh 2B cùng với người bạn đồng hành của cô - 9S, và một kẻ đào tẩu nguyên mẫu. Trò chơi kết hợp yếu tố nhập vai với hành động chiến đấu và nhiều loại gameplay khác tương tự với NieR.</br></br>Cấu hình tối thiểu:</br></br>Bộ xử lí Chip I3 thế hệ 4 trở lên</br>Bộ nhớ trong: Ram 4g</br>Card rời tối thiểu 2g thế hệ mới.</br>DirectX: Version 11</br>Network: Broadband Internet connection.</br>Ổ Cứng 250 hoặc ssd 220</br>Tốc độ mạng sử dụng 27m – 45m </br></br>Xin liên hệ hotline: 1900-8888 để được hỗ trợ tốt nhất.");
sp[7] = new sanpham("7","TT CT","Pro Evolution Soccer 2019 - PES2019","1.290.000","./img/content/pes19/pes19-0.jpg","Giới thiệu về game:</br></br>-Trò chơi mô phỏng bóng đá.</br></br>Cấu hình tối thiểu:</br></br>Bộ xử lí Chip I3 thế hệ 4 trở lên</br>Bộ nhớ trong: Ram 4g</br>Card rời tối thiểu 2g thế hệ mới.</br>DirectX: Version 11</br>Network: Broadband Internet connection.</br>Ổ Cứng 250 hoặc ssd 220</br>Tốc độ mạng sử dụng 27m – 45m </br></br>Xin liên hệ hotline: 1900-8888 để được hỗ trợ tốt nhất.");
sp[8] = new sanpham("8","NV PL TGM","The Witcher 3: Wild Hunt - Game of the Year Edition","369.000","./img/content/tw3/tw3-0.jpg","Giới thiệu về game:</br></br>-The Witcher 3: Wild Hunt là một thế giới khắc nghiệt: quái vật hoành hành, con người nghi kị lẫn nhau, mảnh đất này lúc nào cũng nhuộm đỏ máu vì chiến tranh. Bước vào một nơi như vậy, người chơi lúc nào cũng phải chuẩn bị tâm thế sẵn sàng đánh nhau bất cứ lúc nào. Một trong những điều khiến game thủ thấy băn khoăn là hệ thống chiêu thức quá rộng, chia thành 4 mục lớn với 70 kỹ năng khác nhau, mỗi kỹ năng lại có tối thiểu 2 và tối đa là 5 cấp độ. Vì thế, lựa chọn kỹ năng để nâng cấp thôi cũng đủ để khiến người chơi phải đau đầu. Vì thế bài viết ngày hôm nay sẽ hướng dẫn game thủ xây dựng hệ thống kỹ năng hiệu quả nhất dựa vào phong cách chiến đấu của mỗi người.</br></br>Cấu hình tối thiểu:</br></br>Bộ xử lí Chip I3 thế hệ 4 trở lên</br>Bộ nhớ trong: Ram 4g</br>Card rời tối thiểu 2g thế hệ mới.</br>DirectX: Version 11</br>Network: Broadband Internet connection.</br>Ổ Cứng 250 hoặc ssd 220</br>Tốc độ mạng sử dụng 27m – 45m </br></br>Xin liên hệ hotline: 1900-8888 để được hỗ trợ tốt nhất.");
sp[9] = new sanpham("9","VT PL ST TGM ID","No Man's Sky","440.000","./img/content/nms/nms-0.jpg","Giới thiệu về game:</br></br>-Đây là một trò chơi tồn tại trên một thế giới mở, hướng đi của nó tập trung vào việc thăm dò, thám hiểm và khám phá. Nó đã thu hút sự chú ý của những nhà truyền thông lớn. Nhà phát triển của tựa game cũng cho biết sẽ phải mất tới 5 tỉ năm thời gian thật để có thể khám phá hết 18 tỷ tỷ hành tinh. Nói cách khác, có một khả năng cho thấy No Man's Sky sẽ là video games lớn nhất từng được tạo ra.</br></br>Cấu hình tối thiểu:</br></br>Bộ xử lí Chip I3 thế hệ 4 trở lên</br>Bộ nhớ trong: Ram 4g</br>Card rời tối thiểu 2g thế hệ mới.</br>DirectX: Version 11</br>Network: Broadband Internet connection.</br>Ổ Cứng 250 hoặc ssd 220</br>Tốc độ mạng sử dụng 27m – 45m </br></br>Xin liên hệ hotline: 1900-8888 để được hỗ trợ tốt nhất.");
sp[10] = new sanpham("10","ST TGM ID","The Forest","188.000","./img/content/tf/tf-0.jpg","Giới thiệu về game:</br></br>-The Forest là tựa game kinh dị sinh tồn thế giới mở không chỉ ấn tượng về đồ họa “rừng thiên nước độc” mà cả gameplay cũng là điểm thu hút người chơi. ... Trong tay không gì khác ngoài một chiếc rìu nhỏ và quyển sách hướng dẫn sinh tồn nơi thiên nhiên hoang dã, người chơi phải sử dụng kiến thức trong đó để sinh tồn.</br></br>Cấu hình tối thiểu:</br></br>Bộ xử lí Chip I3 thế hệ 4 trở lên</br>Bộ nhớ trong: Ram 4g</br>Card rời tối thiểu 2g thế hệ mới.</br>DirectX: Version 11</br>Network: Broadband Internet connection.</br>Ổ Cứng 250 hoặc ssd 220</br>Tốc độ mạng sử dụng 27m – 45m </br></br>Xin liên hệ hotline: 1900-8888 để được hỗ trợ tốt nhất.");
sp[11] = new sanpham("11","ST TGM ID","RUST","280.000","./img/content/rust/rust-0.jpg","Giới thiệu về game:</br></br>-Rust là một game thể loại sinh tồn được tạo bởi Facepunch Studios. Lấy cảm hứng từ trò chơi như Dayz, Minecraft và Stalker. Rust hướng tới một môi trường khắc nghiệt, nơi mà người chơi phải đấu tranh để sống sót từng ngày trong đó.</br></br>Mục tiêu cao cả của game là sống sót. Để làm được điều đó người chơi phải thu thập tài nguyên như gỗ, đá, tạo ra một đống lửa để chống lại cái lạnh giá, tạo nên một ngôi nhà để trú thân hay săn bắn thú kiếm thịt ăn để sinh tồn. Ngoài ra bạn còn phải chống trọi lại những bầy thú dữ, những bầy zombie và cả những người chơi khác. Rust đem bạn tới một thế giới tuyệt đẹp, nơi có những thảo nguyên xanh mượt, những ngọn núi hùng vĩ, những cánh rừng bát ngát. Ngoài ra trong Rust bạn không khó để gặp những công trình mang dấu tay của con người ví dụ như những con đường và những khu nhà máy bỏ hoang.</br></br>Rust là một tựa game sinh tồn Multiplayer, sẽ không có phần chơi Single. Chính vì vậy mà bạn rất dễ kết nối được với nhiều bạn bè cùng tham gia trong thế giới game này. Bạn có thể chơi cùng bạn bè, người thân. Thậm chí còn có thể kết nối và cùng chơi với những người bạn chơi xa lạ. Cùng nhau sinh tồn đôi lúc còn có thể giết lẫn nhau.</br></br>Cấu hình tối thiểu:</br></br>Bộ xử lí Chip I3 thế hệ 4 trở lên</br>Bộ nhớ trong: Ram 4g</br>Card rời tối thiểu 2g thế hệ mới.</br>DirectX: Version 11</br>Network: Broadband Internet connection.</br>Ổ Cứng 250 hoặc ssd 220</br>Tốc độ mạng sử dụng 27m – 45m </br></br>Xin liên hệ hotline: 1900-8888 để được hỗ trợ tốt nhất.");
sp[12] = new sanpham("12","CT ID ST","Oxygen Not Included","220.000","./img/content/oni/oni-0.jpg","Giới thiệu về game:</br></br>-Oxy không bao gồm là một trò chơi tồn tại mô phỏng . [4] Khi bắt đầu một trò chơi mới, ba người thực dân tìm thấy chính mình trong một tiểu hành tinh với các túi khí quyển thoáng đãng, không có ký ức về cách họ đến đó. Người chơi có nhiệm vụ quản lý và chăm sóc những người thực dân này khi họ cố gắng sống sót và tạo ra một thuộc địa không gian tạm thời bền vững . Người chơi phải theo dõi các mức độ đói, chất thải và oxy của thực dân để giữ cho chúng sống sót. [4] Thế giới của mỗi trò chơi được tạo ra theo cách thủ tục . [4] Trong khi các khu vực ban đầu sẽ bao gồm bầu không khí thoáng khí, các khu vực trên thế giới sẽ ở trong chân khônghoặc thiếu oxy, đòi hỏi phải chuẩn bị thích hợp bởi những người thực dân trước khi họ khám phá những khu vực này. Trò chơi mô phỏng sự khuếch tán của khí và cân bằng của khí quyển khi một buồng tự nhiên mới được mở ra, có thể gây ra mức oxy giảm trong các phòng hiện có, cũng như sự thoát nước của chất lỏng bằng trọng lực....</br></br>Cấu hình tối thiểu:</br></br>Bộ xử lí Chip I3 thế hệ 4 trở lên</br>Bộ nhớ trong: Ram 4g</br>Card rời tối thiểu 2g thế hệ mới.</br>DirectX: Version 11</br>Network: Broadband Internet connection.</br>Ổ Cứng 250 hoặc ssd 220</br>Tốc độ mạng sử dụng 27m – 45m </br></br>Xin liên hệ hotline: 1900-8888 để được hỗ trợ tốt nhất.");
sp[13] = new sanpham("13","GL","Thief Simulator","188.000","./img/content/ts/ts-0.jpg","Giới thiệu về game:</br></br>------</br></br>Cấu hình tối thiểu:</br></br>Bộ xử lí Chip I3 thế hệ 4 trở lên</br>Bộ nhớ trong: Ram 4g</br>Card rời tối thiểu 2g thế hệ mới.</br>DirectX: Version 11</br>Network: Broadband Internet connection.</br>Ổ Cứng 250 hoặc ssd 220</br>Tốc độ mạng sử dụng 27m – 45m </br></br>Xin liên hệ hotline: 1900-8888 để được hỗ trợ tốt nhất.");
sp[14] = new sanpham("14","GL","Hand Simulator","30.000","./img/content/hs/hs-0.jpg","Giới thiệu về game:</br></br>------</br></br>Cấu hình tối thiểu:</br></br>Bộ xử lí Chip I3 thế hệ 4 trở lên</br>Bộ nhớ trong: Ram 4g</br>Card rời tối thiểu 2g thế hệ mới.</br>DirectX: Version 11</br>Network: Broadband Internet connection.</br>Ổ Cứng 250 hoặc ssd 220</br>Tốc độ mạng sử dụng 27m – 45m </br></br>Xin liên hệ hotline: 1900-8888 để được hỗ trợ tốt nhất.");
sp[15] = new sanpham("15","HD NV TGM","Yakuza 0","342.000","./img/content/ykz0/ykz0-0.jpg","Giới thiệu về game:</br></br>-Yakuza 0 là một trò chơi phiêu lưu hành động được đặt trong một môi trường thế giới mở và được chơi từ góc độ người thứ ba . Người chơi điều khiển nhân vật chính Kazuma Kiryu và nhân vật lặp lại Goro Majima, xen kẽ giữa hai nhân vật ở những điểm định trước trong câu chuyện.</br></br>Người chơi có thể tự do dạo quanh Kamurocho và Sotenbori, tương tác với những người mà họ gặp để kích hoạt các nhiệm vụ phụ , chiến đấu với kẻ thù tấn công họ trên đường phố, hoặc chơi một trong vài minigame, bao gồm các phiên bản trò chơi Sega hoàn toàn có thể chơi được như Out Run , Super Hang-On , Space Harrier và Fantasy Zone . Hoàn thành một số mục tiêu nhất định, chẳng hạn như ăn tất cả các món ăn tại một nhà hàng hoặc đạt được điểm mục tiêu trong một minigame, cũng sẽ cấp cho người chơi tiền hoàn thành tiền đặc biệt; CP này có thể được chi tiêu tại một đền thờ để nhận thêm tiền thưởng, chẳng hạn như các vật phẩm đặc biệt hoặc nâng cấp nhân vật.</br></br>Cấu hình tối thiểu:</br></br>Bộ xử lí Chip I3 thế hệ 4 trở lên</br>Bộ nhớ trong: Ram 4g</br>Card rời tối thiểu 2g thế hệ mới.</br>DirectX: Version 11</br>Network: Broadband Internet connection.</br>Ổ Cứng 250 hoặc ssd 220</br>Tốc độ mạng sử dụng 27m – 45m </br></br>Xin liên hệ hotline: 1900-8888 để được hỗ trợ tốt nhất.");
sp[16] = new sanpham("16","NV PL TGM FPS","Fallout 4: Game of the Year Edition","480.000","./img/content/fo4/fo4-0.jpg","Giới thiệu về game:</br></br>-Người chơi giả định quyền kiểm soát của một nhân vật được gọi là -Người sống sót duy nhất-, người nổi lên từ một chuồng đông lạnh dài hạn trong Vault 111, một nơi trú ẩn hạt nhân dưới đất. Sau khi chứng kiến ​​vụ giết người vợ / chồng của họ và bắt cóc con trai của họ, những người sống sót duy nhất mạo hiểm ra ngoài vào Khối thịnh vượng chung để tìm kiếm đứa con mất tích của họ. Người chơi khám phá thế giới đổ nát của trò chơi, hoàn thành các nhiệm vụ khác nhau, giúp các phe phái, và thu thập điểm kinh nghiệm để tăng cấp và tăng khả năng của nhân vật của họ. Các tính năng mới của loạt sản phẩm bao gồm khả năng phát triển và quản lý các khu định cư và hệ thống chế tạo rộng rãi, nơi các vật liệu nhặt rác từ môi trường có thể được sử dụng để chế tạo thuốc và chất nổ, nâng cấp vũ khí và áo giáp, và xây dựng, cung cấp và cải thiện các khu định cư.</br></br>Cấu hình tối thiểu:</br></br>Bộ xử lí Chip I3 thế hệ 4 trở lên</br>Bộ nhớ trong: Ram 4g</br>Card rời tối thiểu 2g thế hệ mới.</br>DirectX: Version 11</br>Network: Broadband Internet connection.</br>Ổ Cứng 250 hoặc ssd 220</br>Tốc độ mạng sử dụng 27m – 45m </br></br>Xin liên hệ hotline: 1900-8888 để được hỗ trợ tốt nhất.");
sp[17] = new sanpham("17","NV PL TGM","The Elder Scrolls V: Skyrim Special Edition","900.000","./img/content/tesv/tesv-0.jpg","Giới thiệu về game:</br></br>-Cốt truyện của Skyrim xoay quanh hành trình nhân vật của người chơi đánh bại Alduin, một con rồng được tiên đoán là sẽ hủy diệt thế giới. Xảy ra 200 năm sau Oblivion, trò chơi lấy bối cảnh tại tỉnh Skyrim hư cấu nằm trên lục địa Tamriel của hành tinh Nirn. Lối chơi thế giới mở của loạt trò chơi The Elder Scrolls tiếp tục trở lại ở Skyrim; người chơi có thể bỏ qua hoặc trì hoãn cốt truyện để tự do khám phá. </br></br>Cấu hình tối thiểu:</br></br>Bộ xử lí Chip I3 thế hệ 4 trở lên</br>Bộ nhớ trong: Ram 4g</br>Card rời tối thiểu 2g thế hệ mới.</br>DirectX: Version 11</br>Network: Broadband Internet connection.</br>Ổ Cứng 250 hoặc ssd 220</br>Tốc độ mạng sử dụng 27m – 45m </br></br>Xin liên hệ hotline: 1900-8888 để được hỗ trợ tốt nhất.");
sp[18] = new sanpham("18","NV PL TGM KD FPS","Dying Light Enhanced Edition","549.000","./img/content/dl/dl-0.jpg","Giới thiệu về game:</br></br>-Trong Dying Light: The Following, bạn phải tìm cách lấy được lòng tin từ phía Children of the Sun, kết quả là người chơi sẽ phải một lần nữa thực hiện hàng tá việc vặt và nhiệm vụ phụ khiến Kyle Crane chả khác nào… hướng đạo sinh. May mắn thay, đa phần các nhiệm vụ trong Dying Light: The Following kỳ này đều sở hữu nội dung được chăm chút kỹ càng hơn (Techland học tập từ người anh em cùng nhà CD Projekt RED chăng?) và không chỉ gói gọn trong mô hình “fetch quest”, khiến cho game ít mang cảm giác lặp lại như trước cũng như tạo nên một câu chuyện kỳ bí, hấp dẫn và thật sự rùng rợn hơn. Góp phần giúp đổi mới lối chơi trong Dying Light: The Following là bối cảnh nông thôn bao gồm những cánh đồng rộng lớn và những tuyến đường nối liền nhau, khiến cho súng ống trong game – đặc biệt là cây nỏ, có đất dụng võ nhiều hơn.</br></br>Cấu hình tối thiểu:</br></br>Bộ xử lí Chip I3 thế hệ 4 trở lên</br>Bộ nhớ trong: Ram 4g</br>Card rời tối thiểu 2g thế hệ mới.</br>DirectX: Version 11</br>Network: Broadband Internet connection.</br>Ổ Cứng 250 hoặc ssd 220</br>Tốc độ mạng sử dụng 27m – 45m </br></br>Xin liên hệ hotline: 1900-8888 để được hỗ trợ tốt nhất.");
sp[19] = new sanpham("19","NV KD","RESIDENT EVIL 7 biohazard / BIOHAZARD 7 resident evil","398.000","./img/content/re7/re7-0.jpg","Giới thiệu về game:</br></br>-Resident Evil 7 trở lại với nguồn gốc kinh dị sinh tồn của franchise, nhấn mạnh việc khám phá. Người chơi điều khiển Ethan Winterskhi anh tìm kiếm vợ mình trong một đồn điền vô chủ bị chiếm đóng bởi một gia đình ăn thịt người, giải quyết các câu đố và chiến đấu với kẻ thù.</br></br>Cấu hình tối thiểu:</br></br>Bộ xử lí Chip I3 thế hệ 4 trở lên</br>Bộ nhớ trong: Ram 4g</br>Card rời tối thiểu 2g thế hệ mới.</br>DirectX: Version 11</br>Network: Broadband Internet connection.</br>Ổ Cứng 250 hoặc ssd 220</br>Tốc độ mạng sử dụng 27m – 45m </br></br>Xin liên hệ hotline: 1900-8888 để được hỗ trợ tốt nhất. ");
sp[20] = new sanpham("20","TT","NBA 2K19","984.000","./img/content/nba19/nba19-0.jpg","Giới thiệu về game:</br></br>-NBA 2K19 là một trò chơi mô phỏng bóng rổ.</br></br>Cấu hình tối thiểu:</br></br>Bộ xử lí Chip I3 thế hệ 4 trở lên</br>Bộ nhớ trong: Ram 4g</br>Card rời tối thiểu 2g thế hệ mới.</br>DirectX: Version 11</br>Network: Broadband Internet connection.</br>Ổ Cứng 250 hoặc ssd 220</br>Tốc độ mạng sử dụng 27m – 45m </br></br>Xin liên hệ hotline: 1900-8888 để được hỗ trợ tốt nhất.");
sp[21] = new sanpham("21","NV PL TGM","Assassin's Creed® Odyssey","990.000","./img/content/aco/aco-0.jpg","Giới thiệu về game:</br></br>----</br></br>Cấu hình tối thiểu:</br></br>Bộ xử lí Chip I3 thế hệ 4 trở lên</br>Bộ nhớ trong: Ram 4g</br>Card rời tối thiểu 2g thế hệ mới.</br>DirectX: Version 11</br>Network: Broadband Internet connection.</br>Ổ Cứng 250 hoặc ssd 220</br>Tốc độ mạng sử dụng 27m – 45m </br></br>Xin liên hệ hotline: 1900-8888 để được hỗ trợ tốt nhất.");
sp[22] = new sanpham("22","HD NV","HITMAN™ 2","990.000","./img/content/hm2/hm2-0.jpg","Giới thiệu về game:</br></br>-Hitman tạo nên một sân chơi mà trong đó, người chơi vừa đóng vai trò là “game master”, vừa là người tham gia cuộc chơi. Bạn không chỉ thâm nhập vào hành vi của NPC và quãng hoạt động của mọi thứ trong game, bạn tự tay “chọc ngoáy” nó như một thợ máy, xoay chuyển nó về hướng có lợi cho mình như một vị tướng, “hô biến” nó và tạo nên một màn trình diễn đẹp mắt như một ảo thuật gia. Tất cả mọi thứ về Hitman đều muốn người chơi thử nghiệm theo cách sáng tạo và tự do nhất có thể.</br></br>Cấu hình tối thiểu:</br></br>Bộ xử lí Chip I3 thế hệ 4 trở lên</br>Bộ nhớ trong: Ram 4g</br>Card rời tối thiểu 2g thế hệ mới.</br>DirectX: Version 11</br>Network: Broadband Internet connection.</br>Ổ Cứng 250 hoặc ssd 220</br>Tốc độ mạng sử dụng 27m – 45m </br></br>Xin liên hệ hotline: 1900-8888 để được hỗ trợ tốt nhất.");
sp[23] = new sanpham("23","HD NV FPS","Battlefield V","1.350.000","./img/content/bf5/bf5-0.jpg","Giới thiệu về game:</br></br>-Battlefield V là game bắn súng....</br></br>Cấu hình tối thiểu:</br></br>Bộ xử lí Chip I3 thế hệ 4 trở lên</br>Bộ nhớ trong: Ram 4g</br>Card rời tối thiểu 2g thế hệ mới.</br>DirectX: Version 11</br>Network: Broadband Internet connection.</br>Ổ Cứng 250 hoặc ssd 220</br>Tốc độ mạng sử dụng 27m – 45m </br></br>Xin liên hệ hotline: 1900-8888 để được hỗ trợ tốt nhất.");
sp[24] = new sanpham("24","PL NV TGM","Darksiders III","620.000","./img/content/ds3/ds3-0.jpg","Giới thiệu về game:</br></br>-Darksiders III là một game phiêu lưu hành động . Người chơi nắm quyền kiểm soát Fury, em gái của War and Death, hai trong số Four Horsemen of the Apocalypse , từ góc độ người thứ ba . Fury, một pháp sư được mô tả là người không thể đoán trước và bí ẩn nhất của Four Horsemen, dựa vào roi, kiếm, cánh, dao găm và ma thuật trong chiến đấu. [1] [2] Fury có thể sử dụng nhiều dạng nguyên tố khác nhau để tăng cường khả năng chiến đấu của mình bằng cách cấp vũ khí, tấn công và khả năng di chuyển mới của cô. Một trong nhiều dạng này là dạng Ngọn lửa.</br></br>Cấu hình tối thiểu:</br></br>Bộ xử lí Chip I3 thế hệ 4 trở lên</br>Bộ nhớ trong: Ram 4g</br>Card rời tối thiểu 2g thế hệ mới.</br>DirectX: Version 11</br>Network: Broadband Internet connection.</br>Ổ Cứng 250 hoặc ssd 220</br>Tốc độ mạng sử dụng 27m – 45m </br></br>Xin liên hệ hotline: 1900-8888 để được hỗ trợ tốt nhất.");
sp[25] = new sanpham("25","PL NV TGM","Just Cause 4","1.291.500","./img/content/jc4/jc4-0.jpg","Giới thiệu về game:</br></br>-Rico Rodriguez cầm lấy Black Hand, đội quân tư nhân mạnh nhất thế giới do Gabriella Morales điều hành, một nhân vật mới được giới thiệu. The Black Hand phục vụ như một nhóm lính đánh thuê cho các nhà độc tài Salvador Mendoza của Just Cause và Sebastiano Di Ravello trong Just Cause 3 . Khi Rico được chứng minh rằng người cha quá cố của anh đang làm việc với The Black Hand, anh lao vào quốc gia Nam Mỹ của Solís, quê hương của Black Hand để tìm kiếm câu trả lời.</br></br>Cấu hình tối thiểu:</br></br>Bộ xử lí Chip I3 thế hệ 4 trở lên</br>Bộ nhớ trong: Ram 4g</br>Card rời tối thiểu 2g thế hệ mới.</br>DirectX: Version 11</br>Network: Broadband Internet connection.</br>Ổ Cứng 250 hoặc ssd 220</br>Tốc độ mạng sử dụng 27m – 45m </br></br>Xin liên hệ hotline: 1900-8888 để được hỗ trợ tốt nhất. ");
sp[26] = new sanpham("26","ST CT KD","Dead by Daylight","188.000","./img/content/dbd/dbd-0.jpg","Giới thiệu về game:</br></br>-Dead by Daylight là một tựa game multiplayer mới ra mắt mà trong đó người chơi chia làm hai phe: Một bên là nhóm 4 nhân vật yếu đuối không có khả năng chiến đấu đối mặt với gã sát nhân hàng loạt điên khùng do một game thủ khác điều khiển. Nhóm người thường cần ẩn nấp, chạy trốn và kích hoạt các máy phát điện nhằm mở cánh cổng trốn thoát khỏi khu rừng, trong khi gã đồ tể cần phải săn tìm bằng được họ trước khi điều nói trên xảy ra.</br></br>Cấu hình tối thiểu:</br></br>Bộ xử lí Chip I3 thế hệ 4 trở lên</br>Bộ nhớ trong: Ram 4g</br>Card rời tối thiểu 2g thế hệ mới.</br>DirectX: Version 11</br>Network: Broadband Internet connection.</br>Ổ Cứng 250 hoặc ssd 220</br>Tốc độ mạng sử dụng 27m – 45m </br></br>Xin liên hệ hotline: 1900-8888 để được hỗ trợ tốt nhất.");
sp[27] = new sanpham("27","ID KD","Visage","220.000","./img/content/vsg/vsg-0.jpg","Giới thiệu về game:</br></br>----</br></br>Cấu hình tối thiểu:</br></br>Bộ xử lí Chip I3 thế hệ 4 trở lên</br>Bộ nhớ trong: Ram 4g</br>Card rời tối thiểu 2g thế hệ mới.</br>DirectX: Version 11</br>Network: Broadband Internet connection.</br>Ổ Cứng 250 hoặc ssd 220</br>Tốc độ mạng sử dụng 27m – 45m </br></br>Xin liên hệ hotline: 1900-8888 để được hỗ trợ tốt nhất.");
sp[28] = new sanpham("28","ST FPS KD","Left 4 Dead 2","120.000","./img/content/l4d2/l4d2-0.jpg","Giới thiệu về game:</br></br>-Đến với game Left 4 Dead 2 bạn có thể lựa chọn 1 trong 4 nhân vật để nhập vai: Rochelle, Rochelle, Ellis, Nick. Rochelle là đạo diễn truyền hình, Coach là thầy giáo thể dục, Ellis là anh chàng thợ máy và Nick một kẻ nghiện cờ bạc. Mỗi nhân vật sẽ mang những khả năng, tính cách cũng như có những đặc điểm riêng biệt nhưng tất cả đều chiến đấu với mục đích duy nhất chính là sinh tồn.</br></br>Cấu hình tối thiểu:</br></br>Bộ xử lí Chip I3 thế hệ 4 trở lên</br>Bộ nhớ trong: Ram 4g</br>Card rời tối thiểu 2g thế hệ mới.</br>DirectX: Version 11</br>Network: Broadband Internet connection.</br>Ổ Cứng 250 hoặc ssd 220</br>Tốc độ mạng sử dụng 27m – 45m </br></br>Xin liên hệ hotline: 1900-8888 để được hỗ trợ tốt nhất.");
sp[29] = new sanpham("29","ST PL VT","Subnautica","220.000","./img/content/sn/sn-0.jpg","Giới thiệu về game:</br></br>Subnautica là một trò chơi được phát triển bởi Unknown Worlds Entertainment xây dựng trên chủ đề thám hiểm đại dương. Trong game bạn sẽ trở thành một phi hành gia sống sót sau một vụ tai nạn và con tàu của bạn bị rơi xuống biển của một hành tinh xa lạ, bạn sẽ tận sử dụng chiếc thuyền cứu sinh trên tàu và lênh đênh trên đại dương bao la tìm nguồn sống và đi tìm đồng đội. Bạn sẽ phải đi thu thập nguyên liệu tự tạo ra những thứ đồ thiết yếu như đồ lặn, bình oxi hay đèn pin để đi vào ban đêm...</br></br>Cấu hình tối thiểu:</br></br>Bộ xử lí Chip I3 thế hệ 4 trở lên</br>Bộ nhớ trong: Ram 4g</br>Card rời tối thiểu 2g thế hệ mới.</br>DirectX: Version 11</br>Network: Broadband Internet connection.</br>Ổ Cứng 250 hoặc ssd 220</br>Tốc độ mạng sử dụng 27m – 45m </br></br>Xin liên hệ hotline: 1900-8888 để được hỗ trợ tốt nhất.");
sp[30] = new sanpham("30","ST PL VT","ASTRONEER","280.000","./img/content/ast/ast-0.jpg","Giới thiệu về game:</br></br>-Astroneer là tựa game thám hiểm vũ trụ với một chút gia vị sinh tồn được kết hợp tài tình sẽ là lựa chọn hoàn hảo cho bạn vào cuối tuần này.</br></br>Trong game, bạn có thể tự mình khám phá vũ trụ rộng lớn hoặc co-op cùng với bạn bè của mình trong chế độ online của game. Khởi đầu trò chơi, bạn sẽ thấy mình trên một phi thuyền không gian, chỉ túi đựng đồ cùng một ít công cụ bạn để bạn bắt đầu khám phá hành tinh này,  bạn sẽ tìm kiếm các nguồn tài nguyên, các nguyên vật liệu để xây dựng lên căn cứ và khám phá các công nghệ mới.</br></br>Astroneer cho phép bạn chỉnh sửa lại không gian xung quanh bạn. Tính năng này khá hay, nó rất giống với tựa game chết yểu của Microsoft – Everquest Landmark. Mình rất thích cái này,nhưng còn khá ít tuỳ biến, sẽ hay hơn nếu nhà phát triển cho phép chúng ta tự do tuỳ biến theo ý thích.</br></br>Đây thực sự là một game đốt thời gian, mình đã mất hàng giờ đồng hồ để tìm cách tối ưu căn cứ, xây dựng nó cho đẹp hơn. Những cơn bão trong game cũng rất dữ tợn, nó thâm chí có thể giết người với những mảnh vỡ bay khắp nơi. Ngoài ra, một số loài thực vật có thể giết chết bạn nếu không cẩn thận. Các yếu tố sinh tồn trong game vẫn chưa có nhiều, nhưng chắc chắn sẽ được bổ sung vì game đang trong giai đoạn thử nghiệm mà.</br></br>Cá nhân mình thì mình thích tự kì với máy hơn, nhưng nếu bạn tìm được những người bạn để cùng chơi thì sự thú vị sẽ tăng lên rất nhiều lần. Mặc dù có vài vấn đề khi bạn co-op cũng những người chơi khác. Game hiện tối ưu chưa được tốt nên hãy chắc chắn là máy host game phải thật mạnh, nếu không thì game sẽ khá lag do tuột FPS, và đôi khi bạn sẽ gặp trường hợp rớt mạng nếu như đường truyền máy host không tốt.</br></br>Cấu hình tối thiểu:</br></br>Bộ xử lí Chip I3 thế hệ 4 trở lên</br>Bộ nhớ trong: Ram 4g</br>Card rời tối thiểu 2g thế hệ mới.</br>DirectX: Version 11</br>Network: Broadband Internet connection.</br>Ổ Cứng 250 hoặc ssd 220</br>Tốc độ mạng sử dụng 27m – 45m </br></br>Xin liên hệ hotline: 1900-8888 để được hỗ trợ tốt nhất.");
sp[31] = new sanpham("31","VT GL","Jurassic World Evolution","1.252.000","./img/content/jwe/jwe-0.jpg","Giới thiệu về game:</br></br>-Jurassic World Evolution là một tựa game mô phỏng xây dựng công viên giải trí, với sự xuất hiện của 40 chủng loài khủng long khác nhau trên 5 hòn đảo. Bạo chúa T-Rex, raptors, Tricerator, Brachiosaurus,… sẽ là một trong số đó. Điều đáng tiếc là nó sẽ ra mắt mà không hỗ trợ mod, phần nào giảm đi sự sáng tạo đến từ cộng đồng.</br></br>Cấu hình tối thiểu:</br></br>Bộ xử lí Chip I3 thế hệ 4 trở lên</br>Bộ nhớ trong: Ram 4g</br>Card rời tối thiểu 2g thế hệ mới.</br>DirectX: Version 11</br>Network: Broadband Internet connection.</br>Ổ Cứng 250 hoặc ssd 220</br>Tốc độ mạng sử dụng 27m – 45m </br></br>Xin liên hệ hotline: 1900-8888 để được hỗ trợ tốt nhất.");
sp[32] = new sanpham("32","FPS VT","Portal 2","120.000","./img/content/pt2/pt2-0.jpg","Giới thiệu về game:</br></br>-Game sắp ra mắt đặt trước để hưởng ưu đãi từ 4Tshop nhé!!!</br></br>Cấu hình tối thiểu:</br></br>Bộ xử lí Chip I3 thế hệ 4 trở lên</br>Bộ nhớ trong: Ram 4g</br>Card rời tối thiểu 2g thế hệ mới.</br>DirectX: Version 11</br>Network: Broadband Internet connection.</br>Ổ Cứng 250 hoặc ssd 220</br>Tốc độ mạng sử dụng 27m – 45m </br></br>Xin liên hệ hotline: 1900-8888 để được hỗ trợ tốt nhất.");
sp[33] = new sanpham("33","PL NV TGM","FINAL FANTASY XV WINDOWS EDITION","1.135.000","./img/content/ffxv/ffxv-0.jpg","Giới thiệu về game:</br></br>-Final Fantasy XV diễn ra trong một thế giới tương tự như Trái Đất ngày nay. Các quốc gia trên thế giới một lần nữa đã tiến hành chiến tranh giành quyền kiểm soát các viên tinh thể của thế giới, và tất cả ngoại trừ quốc gia của Lucis đành cam chịu thua cuộc và thụt lùi xuống xã hội như thời Trung cổ. Noctis Lucis Caelum, một hoàng tử của vương quốc Lucis có được quyền năng ma thuật từ lần bị kinh nghiệm cận tử.Trong lúc rời quê nhà để đến kết hôn với Lunafreya Nox Fleuret (là công chúa của Tenebrae) thì quốc gia quân sự Niflheim bất ngờ xâm lược Lucis vào đêm trước khi diễn ra các cuộc đàm phán hòa bình cuối cùng giữa hai nước.Khi Noctis đã biết được mọi chuyện, anh cùng 3 người bạn quay về bắt đầu hướng tới việc đánh bại các lực lượng của Niflheim và giải cứu những viên tinh thể thoát khỏi sự kiểm soát của họ.</br></br>Cấu hình tối thiểu:</br></br>Bộ xử lí Chip I3 thế hệ 4 trở lên</br>Bộ nhớ trong: Ram 4g</br>Card rời tối thiểu 2g thế hệ mới.</br>DirectX: Version 11</br>Network: Broadband Internet connection.</br>Ổ Cứng 250 hoặc ssd 220</br>Tốc độ mạng sử dụng 27m – 45m </br></br>Xin liên hệ hotline: 1900-8888 để được hỗ trợ tốt nhất.");
sp[34] = new sanpham("34","PL VT","X4: Foundations","440.000","./img/content/x4f/x4f-0.jpg","Giới thiệu về game:</br></br>Game sắp ra mắt đặt trước để hưởng ưu đãi từ 4Tshop nhé!!!</br></br>Cấu hình tối thiểu:</br></br>Bộ xử lí Chip I3 thế hệ 4 trở lên</br>Bộ nhớ trong: Ram 4g</br>Card rời tối thiểu 2g thế hệ mới.</br>DirectX: Version 11</br>Network: Broadband Internet connection.</br>Ổ Cứng 250 hoặc ssd 220</br>Tốc độ mạng sử dụng 27m – 45m </br></br>Xin liên hệ hotline: 1900-8888 để được hỗ trợ tốt nhất.");
sp[35] = new sanpham("35","CT","Artifact","470.000","./img/content/atf/atf-0.jpg","Giới thiệu về game:</br></br>-Là một trò chơi thẻ thu kỹ thuật số , lối chơi của Artifact là xây dựng một cỗ bài có thể thu thập, thu được bằng cách mua thẻ cá nhân hoặc gói của chúng trên Steam Marketplace , để đánh bại đối thủ trong một tình huống trực tiếp. [4] Artifact dựa trên rất nhiều và có nhiều yếu tố từ trò chơi chiến đấu trực tuyến nhiều người chơi DotA 2 , mà Valve cũng phát triển. [5]Như vậy, trò chơi khác với hầu hết các trò chơi thẻ sưu tập truyền thống khác, vì nó có ba -làn đường- được bảo vệ bởi tháp ở cuối, với mỗi làn có sẵn như là bảng độc lập của riêng nó. Người chiến thắng là người đầu tiên phá hủy một cấu trúc gọi là (Cổ đại), xuất hiện sau khi một tòa tháp bị phá hủy, hoặc là người đầu tiên phá hủy hai tòa tháp.</br></br>Cấu hình tối thiểu:</br></br>Bộ xử lí Chip I3 thế hệ 4 trở lên</br>Bộ nhớ trong: Ram 4g</br>Card rời tối thiểu 2g thế hệ mới.</br>DirectX: Version 11</br>Network: Broadband Internet connection.</br>Ổ Cứng 250 hoặc ssd 220</br>Tốc độ mạng sử dụng 27m – 45m </br></br>Xin liên hệ hotline: 1900-8888 để được hỗ trợ tốt nhất. ");

function Card(masp,ten,gia,hinh)
{
	this.masp=masp;
	this.ten=ten;
	this.gia=gia;
	this.hinh=hinh;
}

var card = new Array();
card[0] = new Card("00","Steam Wallet Code 2$","49.000","./img/card/card2.jpg");
card[1] = new Card("01","Steam Wallet Code 5$","122.000","./img/card/card5.jpg");
card[2] = new Card("02","Steam Wallet Code 10$","240.000","./img/card/card10.jpg");
card[3] = new Card("03","Steam Wallet Code 20$","480.000","./img/card/card20.jpg");
card[4] = new Card("04","Steam Wallet Code 50$","1.220.000","./img/card/card50.jpg");
card[5] = new Card("04","Steam Wallet Code 100$","2.300.000","./img/card/card100.jpg");
function View(ma,ten)
{
	this.ma=ma;
	this.ten=ten;
}
var view = new Array();
view[0] = new View("QLTK", "Quản lý tài khoản");
view[1] = new View("DH", "Đơn hàng");
view[2] = new View("DSSP", "Danh sách sản phẩm");

function Thongtin(hoten,mssv,congviec)
{
	this.hoten=hoten;
	this.mssv=mssv;
	this.congviec=congviec;
}
var tt = new Array();
tt[0] = new Thongtin("Ngô Chí Trung","3117410277","Javascript(hiển thị SP, chi tiết SP, trang thông tin, tìm kiếm), Trang admin");
tt[1] = new Thongtin("Hà Thiện Tuấn","3117410285","Javascript(danh mục, kiểm tra ĐN-ĐK, localStorage), Giao diện hoàn thiện(index-ĐN-ĐK), Slideshow, Thông tin SP");
tt[2] = new Thongtin("Vũ Minh Thế","3117410245","Giao diện sơ khai(index-ĐN-ĐK), Banner, Logo, Footer, Chi tiết SP, Giỏ hàng");
tt[3] = new Thongtin("Trần Thanh Toàn","3117410265","Footer, Chi tiết SP, Giỏ hàng");

