function Menu(mamenu, ten) {
    this.mamenu = mamenu;
    this.ten = ten;
}
var m = new Array();
m[0] = new Menu("HD", "Hành động");
m[1] = new Menu("NV", "Nhập vai");
m[2] = new Menu("GL", "Giả lập");
m[3] = new Menu("VT", "Viễn tưởng");
m[4] = new Menu("ID", "Indie");
m[5] = new Menu("PL", "Phiêu lưu");
m[6] = new Menu("KD", "Kinh dị");
m[7] = new Menu("TT", "Thể thao");
m[8] = new Menu("ST", "Sinh tồn");
m[9] = new Menu("FPS", "FPS");
m[10] = new Menu("TGM", "Thế giới mở");
m[11] = new Menu("CT", "Chiến thuật");
function sanpham(masp,mamenu,tengame,gia,hinh,noidung,minhhoa1,minhhoa2)
{
	this.masp=masp;
	this.mamenu=mamenu;
	this.tengame=tengame;
	this.gia=gia;
	this.hinh=hinh;
	this.noidung=noidung;
	this.minhhoa1=minhhoa1;
	this.minhhoa2=minhhoa2;
}
var sp = new Array();
sp[0] = new sanpham("0","HD FPS CT","Counter Strike: Global Offense","140.000","./img/content/csgo/csgo-0.jpg","<b>Mã sản phẩm:</b> csgo-0<br><b>Tình trạng:</b> <span style='color:#27CF2D;'>Còn hàng</span><br><b>Giá:</b> <span style='color:#27CF2D;'>140.000 VNĐ</span><br><br><br><b>GIỚI THIỆU VỀ GAME:</b></br></br> Counter-Strike: Global Offensive (viết tắt là CS:GO) là một trò chơi máy tính thuộc thể loại bắn súng góc nhìn thứ nhất và chiến thuật trực tuyến được phát triển bởi Valve Corporation và Hidden Path Entertainment, đơn vị cũng đã duy trì Counter-Strike: Source sau khi phát hành. Đây là bản thứ tư và cũng là bản mới nhất trong dòng game nổi tiếng Counter-Strike.<br><br><br><b>CẤU HÌNH TỐI THIỂU:</b></br></br>Hệ điều hành: Windows 7 SP1, Windows 8/8.1 (chỉ hỗ trợ 64bit)<br>CPU: Intel Core i5-750 @ 2.6 GHz hoặc AMD Phenom II X4 955 @ 3.2 GHz<br>RAM: 4GB<br>Video card: Hỗ trợ DirectX 11 với 1GB VRAM (NVIDIA GeForce GTX 460 hoặc AMD Radeon HD5850<br>HDD: 10 GB<br>Card âm thanh: 100% DirectX 10 compatible","./img/content/csgo/csgo-1.jpg","./img/content/csgo/csgo-2.jpg");
sp[1] = new sanpham("1","HD ST CT","PLAYERUNKNOWN'S BATTLEGROUNDS","340.000","./img/content/pubg/pubg-0.jpg","<b>Mã sản phẩm:</b> pubg-1<br><b>Tình trạng:</b> <span style='color:#27CF2D;'>Còn hàng</span><br><b>Giá:</b> <span style='color:#27CF2D;'>340.000 VNĐ</span><br><br><br><b>GIỚI THIỆU VỀ GAME:</b></br></br> PLAYERUNKNOWN'S BATTLEGROUNDS là một game bắn súng chiến đấu royale có 100 người chơi với nhau trong một cuộc đấu tranh cho sự sống còn. Thu thập nguồn cung cấp và đánh lừa đối thủ của bạn để trở thành người cuối cùng đứng.<br><br><br><b>CẤU HÌNH TỐI THIỂU:</b></br></br>Hệ điều hành: Windows 7 SP1, Windows 8/8.1 (chỉ hỗ trợ 64bit)<br>CPU: Intel Core i5-750 @ 2.6 GHz hoặc AMD Phenom II X4 955 @ 3.2 GHz<br>RAM: 4GB<br>Video card: Hỗ trợ DirectX 11 với 1GB VRAM (NVIDIA GeForce GTX 460 hoặc AMD Radeon HD5850<br>HDD: 10 GB<br>Card âm thanh: 100% DirectX 10 compatible","./img/content/pubg/pubg-2.jpg","./img/content/pubg/pubg-3.jpg");
sp[2] = new sanpham("2","HD NV TGM","Grand Theft Auto V","380.000","./img/content/gtav/gtav-0.jpg","<b>Mã sản phẩm:</b> gtav-2<br><b>Tình trạng:</b> <span style='color:#27CF2D;'>Còn hàng</span><br><b>Giá:</b> <span style='color:#27CF2D;'>380.000 VNĐ</span><br><br><br><b>GIỚI THIỆU VỀ GAME:</b></br></br>GTA V hay còn được gọi là Grand Theft Auto V là một trong những game được phát triển bởi Rockstar North thuộc hãng Rockstar Games. Là phiên bản thứ mười lăm trong dòng trò chơi Grand Theft Auto và là phần kế tiếp của Grand Theft Auto IV.<br><br><br><b>CẤU HÌNH TỐI THIỂU:</b></br></br>Hệ điều hành: Windows 7 SP1, Windows 8/8.1 (chỉ hỗ trợ 64bit)<br>CPU: Intel Core i5-750 @ 2.6 GHz hoặc AMD Phenom II X4 955 @ 3.2 GHz<br>RAM: 4GB<br>Video card: Hỗ trợ DirectX 11 với 1GB VRAM (NVIDIA GeForce GTX 460 hoặc AMD Radeon HD5850<br>HDD: 65 GB<br>Card âm thanh: 100% DirectX 10 compatible","./img/content/gtav/gtav-1.jpg","./img/content/gtav/gtav-2.jpg");
sp[3] = new sanpham("3","NV PL","MONSTER HUNTER: WORLD","739.000","./img/content/mhw/mhw-0.jpg","<b>Mã sản phẩm:</b> mhw-3<br><b>Tình trạng:</b> <span style='color:#27CF2D;'>Còn hàng</span><br><b>Giá:</b> <span style='color:#27CF2D;'>739.000 VNĐ</span><br><br><br><b>GIỚI THIỆU VỀ GAME:</b></br></br>Được phát hành vào đầu năm 2018, Capcom đã thực sự mang đến cho người chơi một tựa game săn quái mang tầm vóc rộng lớn và nền đồ họa tuyệt đỉnh. Ngoài ra Monster Hunter: World cũng là một trong số hiếm hoi những trò chơi đòi hỏi ‘não của bạn’ phải suy nghĩ và đề ra các chiến thuật hợp lý. Bài đánh giá của chúng tôi hôm nay xin tập trung vào 2 điểm chính: đó là việc săn quái và các nhiệm vụ.<br><br><br><b>CẤU HÌNH TỐI THIỂU:</b></br></br>Hệ điều hành: Windows 7 SP1, Windows 8/8.1 (chỉ hỗ trợ 64bit)<br>CPU: Intel Core i5-750 @ 2.6 GHz hoặc AMD Phenom II X4 955 @ 3.2 GHz<br>RAM: 4GB<br>Video card: Hỗ trợ DirectX 11 với 1GB VRAM (NVIDIA GeForce GTX 460 hoặc AMD Radeon HD5850<br>HDD: 10 GB<br>Card âm thanh: 100% DirectX 10 compatible","./img/content/mhw/mhw-1.jpg","./img/content/mhw/mhw-2.jpg");
sp[4] = new sanpham("4","NV TGM FPS","Far Cry 5 - Standard Edition","914.000","./img/content/fc5/fc5-0.jpg","<b>Mã sản phẩm:</b> fc5-4<br><b>Tình trạng:</b> <span style='color:#27CF2D;'>Còn hàng</span><br><b>Giá:</b> <span style='color:#27CF2D;'>914.000 VNĐ</span><br><br><br><b>GIỚI THIỆU VỀ GAME:</b></br></br>Eden Gate trông có vẻ là một nơi đẹp như tranh vẽ, nhưng tế lại cực kì đen tối. Far Cry 5 đưa bạn vào một vùng đất bị thống trị bởi một giáo xứ do Joseph Seed đứng đầu cùng với những âm mưu xấu xa nhằm thôn tính tinh thần của cả 1 vùng rộng lớn. Nhưng điều đó sẽ chẳng ảnh hướng đến công cuộc khai phá và giải phóng của bạn. Không giống các phiên bản Far Cry trước, bạn có thể truy cập toàn bộ khu vực ngay khi kết thúc nhiệm vụ hướng dẫn, cho phép bạn sử dụng phương tiện, tìm kiếm và hạ gục các tiền đồn của giáo phái. Ngoài ra, đi cùng bạn sẽ bao gồm những con thú vật như sư tử núi, cho hoặc gấu, giúp tiến trình của bạn nhanh hơn rất nhiều.<br><br><br><b>CẤU HÌNH TỐI THIỂU:</b></br></br>Hệ điều hành: Windows 7 SP1, Windows 8/8.1 (chỉ hỗ trợ 64bit)<br>CPU: Intel Core i5-750 @ 2.6 GHz hoặc AMD Phenom II X4 955 @ 3.2 GHz<br>RAM: 4GB<br>Video card: Hỗ trợ DirectX 11 với 1GB VRAM (NVIDIA GeForce GTX 460 hoặc AMD Radeon HD5850<br>HDD: 10 GB<br>Card âm thanh: 100% DirectX 10 compatible","./img/content/fc5/fc5-1.jpg","./img/content/fc5/fc5-2.jpg");
sp[5] = new sanpham("5","HD NV PL","Shadow of the Tomb Raider","1.291.500","./img/content/sottr/sottr-0.jpg","<b>Mã sản phẩm:</b> sottr-5<br><b>Tình trạng:</b> <span style='color:#27CF2D;'>Còn hàng</span><br><b>Giá:</b> <span style='color:#27CF2D;'>1.291.500 VNĐ</span><br><br><br><b>GIỚI THIỆU VỀ GAME:</b></br></br>Shadow of the Tomb Raider là một trò chơi video phiêu lưu hành động được phát triển bởi Eidos Montréal kết hợp với Crystal Dynamics và được phát hành bởi Square Enix. Tiếp tục câu chuyện từ  Rise of the Tomb Raider năm 2015 và là phần chính thức thứ mười hai trong loạt Tomb Raider. Trò chơi được phát hành trên toàn thế giới vào ngày 14 tháng 9 năm 2018 cho Microsoft Windows, PlayStation 4 và Xbox One.<br><br><br><b>CẤU HÌNH TỐI THIỂU:</b></br></br>Hệ điều hành: Windows 7 SP1, Windows 8/8.1 (chỉ hỗ trợ 64bit)<br>CPU: Intel Core i5-750 @ 2.6 GHz hoặc AMD Phenom II X4 955 @ 3.2 GHz<br>RAM: 4GB<br>Video card: Hỗ trợ DirectX 11 với 1GB VRAM (NVIDIA GeForce GTX 460 hoặc AMD Radeon HD5850<br>HDD: 10 GB<br>Card âm thanh: 100% DirectX 10 compatible","./img/content/sottr/sottr-1.jpg","./img/content/sottr/sottr-2.jpg");
sp[6] = new sanpham("6","HD NV PL TGM","NieR:Automata™","1.250.000","./img/content/nier/nier-0.jpg","<b>Mã sản phẩm:</b> nier-6<br><b>Tình trạng:</b> <span style='color:#27CF2D;'>Còn hàng</span><br><b>Giá:</b> <span style='color:#27CF2D;'>1.250.000 VNĐ</span><br><br><br><b>GIỚI THIỆU VỀ GAME:</b></br></br>NieR: Automata là một game hành động nhập vai được phát triển bởi Platinum Games và phát hành bởi Square cho PlayStation 4 và Microsoft. Trò chơi đã phát hành tại Nhật Bản vào tháng 2 năm 2017, và trên toàn thế giới vào tháng sau. NieR: Automata là một phần tiếp theo của trò NieR, một ngoại truyện của dòng game Drakengard . Bối cảnh ở giữa một cuộc chiến tranh giữa các phe phái máy móc với nhau, được tạo ra bởi kẻ xâm lược ngoài hành tinh và tàn dư của nhân loại. Câu truyện về cuộc chiến của một Android chiến đấu biệt danh 2B cùng với người bạn đồng hành của cô - 9S, và một kẻ đào tẩu nguyên mẫu.<br><br><br><b>CẤU HÌNH TỐI THIỂU:</b></br></br>Hệ điều hành: Windows 7 SP1, Windows 8/8.1 (chỉ hỗ trợ 64bit)<br>CPU: Intel Core i5-750 @ 2.6 GHz hoặc AMD Phenom II X4 955 @ 3.2 GHz<br>RAM: 4GB<br>Video card: Hỗ trợ DirectX 11 với 1GB VRAM (NVIDIA GeForce GTX 460 hoặc AMD Radeon HD5850<br>HDD: 10 GB<br>Card âm thanh: 100% DirectX 10 compatible","./img/content/nier/nier-1.jpg","./img/content/nier/nier-2.jpg");
sp[7] = new sanpham("7","TT CT","Pro Evolution Soccer 2019 - PES2019","1.290.000","./img/content/pes19/pes19-0.jpg","<b>Mã sản phẩm:</b> pes19-9<br><b>Tình trạng:</b> <span style='color:#27CF2D;'>Còn hàng</span><br><b>Giá:</b> <span style='color:#27CF2D;'>1.290.000 VNĐ</span><br><br><br><b>GIỚI THIỆU VỀ GAME:</b></br></br>Phiên bản mới nhất của dòng game Pro Evolution Soccer đã trở lại và được đánh giá vô cùng mạnh mẽ hơn bao giờ hết bất chấp những trắc trở về vấn đề bản quyền hình ảnh trưởng lúc ra mắt. 2018 có lẽ không phải là một năm quá vui vẻ cho Konami nói riêng hay công đồng fan hâm mộ dòng game Pro Evolution Soccer nói chung khi có hàng tá những tin tức không vui liên tục kéo đến để làm họ cảm thấy phiền muộn. Tháng 4 có lẽ là quãng thời gian khó chịu nhất khi các thần dân của vương quốc PES nhận được hung tin bản quyền UEFA Champion League và UEFA Europa League sau 10 năm đồng hành đã bị cắt hợp đồng một cách NHANH, GỌN và LẸ...<br><br><br><b>CẤU HÌNH TỐI THIỂU:</b></br></br>Hệ điều hành: Windows 7 SP1, Windows 8/8.1 (chỉ hỗ trợ 64bit)<br>CPU: Intel Core i5-750 @ 2.6 GHz hoặc AMD Phenom II X4 955 @ 3.2 GHz<br>RAM: 4GB<br>Video card: Hỗ trợ DirectX 11 với 1GB VRAM (NVIDIA GeForce GTX 460 hoặc AMD Radeon HD5850<br>HDD: 10 GB<br>Card âm thanh: 100% DirectX 10 compatible","./img/content/pes19/pes19-1.jpg","./img/content/pes19/pes19-2.jpg");
sp[8] = new sanpham("8","NV PL TGM","The Witcher 3: Wild Hunt - Game of the Year Edition","369.000","./img/content/tw3/tw3-0.jpg","<b>Mã sản phẩm:</b> tw3-8<br><b>Tình trạng:</b> <span style='color:#27CF2D;'>Còn hàng</span><br><b>Giá:</b> <span style='color:#27CF2D;'>369.000 VNĐ</span><br><br><br><b>GIỚI THIỆU VỀ GAME:</b></br></br>The Witcher: Wild Hunt là một trò chơi nhập vai thế giới mở, theo câu chuyện thế hệ tiếp theo được đặt trong một vũ trụ tưởng tượng tuyệt đẹp trực quan đầy đủ các lựa chọn có ý nghĩa và hậu quả có ảnh hưởng. Trong The Witcher bạn đóng vai người thợ săn quái vật chuyên nghiệp, Geralt of Rivia, giao nhiệm vụ tìm một đứa trẻ tiên tri trong một thế giới mở rộng giàu có với các thành phố buôn bán, viking đảo cướp biển, đèo núi nguy hiểm và những hang động bị lãng quên để khám phá.<br><br><br><b>CẤU HÌNH TỐI THIỂU:</b></br></br>Hệ điều hành: Windows 7 SP1, Windows 8/8.1 (chỉ hỗ trợ 64bit)<br>CPU: Intel Core i5-750 @ 2.6 GHz hoặc AMD Phenom II X4 955 @ 3.2 GHz<br>RAM: 4GB<br>Video card: Hỗ trợ DirectX 11 với 1GB VRAM (NVIDIA GeForce GTX 460 hoặc AMD Radeon HD5850<br>HDD: 10 GB<br>Card âm thanh: 100% DirectX 10 compatible","./img/content/tw3/tw3-1.jpg","./img/content/tw3/tw3-2.jpg");
sp[9] = new sanpham("9","VT PL ST TGM ID","No Man's Sky","440.000","./img/content/nms/nms-0.jpg","<b>Mã sản phẩm:</b> nms-9<br><b>Tình trạng:</b> <span style='color:#27CF2D;'>Còn hàng</span><br><b>Giá:</b> <span style='color:#27CF2D;'>440.000 VNĐ</span><br><br><br><b>GIỚI THIỆU VỀ GAME:</b></br></br>Lấy cảm hứng từ cuộc phiêu lưu và trí tưởng tượng của những người yêu thích khoa học viễn tưởng cổ điển, No Man's Sky sẽ mang đến cho bạn cả một dải thiên hà để khám phá, tràn ngập những hành tinh và dạng sống độc đáo, và sự nguy hiểm và các trải nghiệm của một cuộc sống hoàn toàn mới trên vũ trụ bao la.<br><br><br><b>CẤU HÌNH TỐI THIỂU:</b></br></br>Hệ điều hành: Windows 7 SP1, Windows 8/8.1 (chỉ hỗ trợ 64bit)<br>CPU: Intel Core i5-750 @ 2.6 GHz hoặc AMD Phenom II X4 955 @ 3.2 GHz<br>RAM: 4GB<br>Video card: Hỗ trợ DirectX 11 với 1GB VRAM (NVIDIA GeForce GTX 460 hoặc AMD Radeon HD5850<br>HDD: 10 GB<br>Card âm thanh: 100% DirectX 10 compatible","./img/content/nms/nms-1.jpg","./img/content/nms/nms-2.jpg");
sp[10] = new sanpham("10","ST TGM ID","The Forest","188.000","./img/content/tf/tf-0.jpg","<b>Mã sản phẩm:</b> tf-10<br><b>Tình trạng:</b> <span style='color:#27CF2D;'>Còn hàng</span><br><b>Giá:</b> <span style='color:#27CF2D;'>188.000 VNĐ</span><br><br><br><b>GIỚI THIỆU VỀ GAME:</b></br></br>The Forest là một tựa game sinh tồn kinh dị nổi tiếng với cốt một cốt truyện hết sức lôi cuốn và hồi hộp. Người chơi sẽ nhập vai một hành khách bị rơi xuống một hòn đảo lạ trong một vụ tai nạn máy bay bí ẩn, và cốt truyện được mở ra khi đứa con trai của ông bị một “người” lạ mặt bắt cóc. Xuyên suốt trò chơi là quá trình sinh tồn cũng như khám phá hòn đảo, người chơi sẽ phải đối mặt với bộ tộc ăn thịt người cùng những con quái vật gớm ghiếc. Tuy nhiên đằng sau hòn đảo tưởng chừng như chỉ chứa sự điên loạn cùng hoang dại lại là một câu chuyện mà không một ai ngờ tới…<br><br><br><b>CẤU HÌNH TỐI THIỂU:</b></br></br>Hệ điều hành: Windows 7 SP1, Windows 8/8.1 (chỉ hỗ trợ 64bit)<br>CPU: Intel Core i5-750 @ 2.6 GHz hoặc AMD Phenom II X4 955 @ 3.2 GHz<br>RAM: 4GB<br>Video card: Hỗ trợ DirectX 11 với 1GB VRAM (NVIDIA GeForce GTX 460 hoặc AMD Radeon HD5850<br>HDD: 10 GB<br>Card âm thanh: 100% DirectX 10 compatible","./img/content/tf/tf-1.jpg","./img/content/tf/tf-2.jpg");
sp[11] = new sanpham("11","ST TGM ID","RUST","280.000","./img/content/rust/rust-0.jpg","<b>Mã sản phẩm:</b> rust-11<br><b>Tình trạng:</b> <span style='color:#27CF2D;'>Còn hàng</span><br><b>Giá:</b> <span style='color:#27CF2D;'>280.000 VNĐ</span><br><br><br><b>GIỚI THIỆU VỀ GAME:</b></br></br>Rust là một game thể loại sinh tồn được tạo bởi Facepunch Studios. Lấy cảm hứng từ trò chơi như Dayz, Minecraft và Stalker. Rust hướng tới một môi trường khắc nghiệt, nơi mà người chơi phải đấu tranh để sống sót từng ngày trong đó.<br><br><br><b>CẤU HÌNH TỐI THIỂU:</b></br></br>Hệ điều hành: Windows 7 SP1, Windows 8/8.1 (chỉ hỗ trợ 64bit)<br>CPU: Intel Core i5-750 @ 2.6 GHz hoặc AMD Phenom II X4 955 @ 3.2 GHz<br>RAM: 4GB<br>Video card: Hỗ trợ DirectX 11 với 1GB VRAM (NVIDIA GeForce GTX 460 hoặc AMD Radeon HD5850<br>HDD: 10 GB<br>Card âm thanh: 100% DirectX 10 compatible","./img/content/rust/rust-1.jpg","./img/content/rust/rust-2.jpg");
sp[12] = new sanpham("12","CT ID ST","Oxygen Not Included","220.000","./img/content/oni/oni-0.jpg","<b>Mã sản phẩm:</b> oni-12<br><b>Tình trạng:</b> <span style='color:#27CF2D;'>Còn hàng</span><br><b>Giá:</b> <span style='color:#27CF2D;'>220.000 VNĐ</span><br><br><br><b>GIỚI THIỆU VỀ GAME:</b></br></br>Trong trò chơi mô phỏng thuộc địa không gian Oxygen Not Included, bạn sẽ thấy rằng sự khan hiếm oxy, sự ấm áp và sự nuôi dưỡng là những mối đe dọa liên tục đến sự tồn tại của thuộc địa của bạn. Hướng dẫn thực dân thông qua các nguy hiểm của tiểu hành tinh dưới lòng đất sống và xem như dân số của họ phát triển cho đến khi họ không chỉ đơn giản là sống sót, nhưng phát triển mạnh ...<br><br><br><b>CẤU HÌNH TỐI THIỂU:</b></br></br>Hệ điều hành: Windows 7 SP1, Windows 8/8.1 (chỉ hỗ trợ 64bit)<br>CPU: Intel Core i5-750 @ 2.6 GHz hoặc AMD Phenom II X4 955 @ 3.2 GHz<br>RAM: 4GB<br>Video card: Hỗ trợ DirectX 11 với 1GB VRAM (NVIDIA GeForce GTX 460 hoặc AMD Radeon HD5850<br>HDD: 10 GB<br>Card âm thanh: 100% DirectX 10 compatible","./img/content/oni/oni-1.jpg","./img/content/oni/oni-2.jpg");
sp[13] = new sanpham("13","GL","Thief Simulator","188.000","./img/content/ts/ts-0.jpg","<b>Mã sản phẩm:</b> ts-13<br><b>Tình trạng:</b> <span style='color:#27CF2D;'>Còn hàng</span><br><b>Giá:</b> <span style='color:#27CF2D;'>188.000 VNĐ</span><br><br><br><b>GIỚI THIỆU VỀ GAME:</b></br></br>Trở thành tên trộm thực sự. Ăn cắp trong khu vực hộp cát đi lang thang miễn phí. Quan sát mục tiêu của bạn và thu thập thông tin sẽ giúp bạn với vụ trộm. Hãy thử thách và cướp ngôi nhà được bảo vệ tốt nhất. Mua một số thiết bị chống trộm công nghệ cao và tìm hiểu các thủ thuật kẻ trộm mới. Bán hàng bị đánh cắp cho người qua đường. Làm bất cứ điều gì mà một tên trộm thực sự làm!<br><br><br><b>CẤU HÌNH TỐI THIỂU:</b></br></br>Hệ điều hành: Windows 7 SP1, Windows 8/8.1 (chỉ hỗ trợ 64bit)<br>CPU: Intel Core i5-750 @ 2.6 GHz hoặc AMD Phenom II X4 955 @ 3.2 GHz<br>RAM: 4GB<br>Video card: Hỗ trợ DirectX 11 với 1GB VRAM (NVIDIA GeForce GTX 460 hoặc AMD Radeon HD5850<br>HDD: 10 GB<br>Card âm thanh: 100% DirectX 10 compatible","./img/content/ts/ts-1.jpg","./img/content/ts/ts-2.jpg");
sp[14] = new sanpham("14","GL","Hand Simulator","30.000","./img/content/hs/hs-0.jpg","<b>Mã sản phẩm:</b> hs-14<br><b>Tình trạng:</b> <span style='color:#27CF2D;'>Còn hàng</span><br><b>Giá:</b> <span style='color:#27CF2D;'>30.000 VNĐ</span><br><br><br><b>GIỚI THIỆU VỀ GAME:</b></br></br>Mô phỏng tay là một trò chơi mà trong đó bạn có thể kiểm soát bàn tay của bạn. Nhiệm vụ của bạn là học cách làm việc bằng ngón tay của bạn tốt, làm thế nào để nắm vững nghệ thuật bắn súng và cố gắng trở thành nhanh nhất và game bắn súng sắc nét nhất trong toàn bộ miền tây hoang dã.<br><br><br><b>CẤU HÌNH TỐI THIỂU:</b></br></br>Hệ điều hành: Windows 7 SP1, Windows 8/8.1 (chỉ hỗ trợ 64bit)<br>CPU: Intel Core i5-750 @ 2.6 GHz hoặc AMD Phenom II X4 955 @ 3.2 GHz<br>RAM: 4GB<br>Video card: Hỗ trợ DirectX 11 với 1GB VRAM (NVIDIA GeForce GTX 460 hoặc AMD Radeon HD5850<br>HDD: 10 GB<br>Card âm thanh: 100% DirectX 10 compatible","./img/content/hs/hs-1.jpg","./img/content/hs/hs-2.jpg");
sp[15] = new sanpham("15","HD NV TGM","Yakuza 0","342.000","./img/content/ykz0/ykz0-0.jpg","<b>Mã sản phẩm:</b> ykz-15<br><b>Tình trạng:</b> <span style='color:#27CF2D;'>Còn hàng</span><br><b>Giá:</b> <span style='color:#27CF2D;'>342.000 VNĐ</span><br><br><br><b>GIỚI THIỆU VỀ GAME:</b></br></br>Yakuza 0 chủ yếu kể về câu chuyện về Rồng Dojima, Kazuma Kiryu, một người đàn ông giỏi dùng nắm đấm làm giải pháp để giải quyết cho mọi vấn đề trong cuộc sống. Chính nó cũng trở thành điểm hấp dẫn cho người chơi yêu thích tựa game hành động thế giời ngầm.<br><br><br><b>CẤU HÌNH TỐI THIỂU:</b></br></br>Hệ điều hành: Windows 7 SP1, Windows 8/8.1 (chỉ hỗ trợ 64bit)<br>CPU: Intel Core i5-750 @ 2.6 GHz hoặc AMD Phenom II X4 955 @ 3.2 GHz<br>RAM: 4GB<br>Video card: Hỗ trợ DirectX 11 với 1GB VRAM (NVIDIA GeForce GTX 460 hoặc AMD Radeon HD5850<br>HDD: 10 GB<br>Card âm thanh: 100% DirectX 10 compatible","./img/content/ykz0/ykz0-1.jpg","./img/content/ykz0/ykz0-2.jpg");
sp[16] = new sanpham("16","NV PL TGM FPS","Fallout 4: Game of the Year Edition","480.000","./img/content/fo4/fo4-0.jpg","<b>Mã sản phẩm:</b> fo4-16<br><b>Tình trạng:</b> <span style='color:#27CF2D;'>Còn hàng</span><br><b>Giá:</b> <span style='color:#27CF2D;'>480.000 VNĐ</span><br><br><br><b>GIỚI THIỆU VỀ GAME:</b></br></br>Lấy bối cảnh thành phố Boston và vùng lân cận hơn 200 năm sau thảm họa chiến tranh hạt nhân, Fallout 4 không những thành công xây dựng nên một thế giới hậu tận thế, mà còn khắc họa nó qua một tương lai giả tưởng với một cách rất sống động và vô cùng thuyết phục.<br><br><br><b>CẤU HÌNH TỐI THIỂU:</b></br></br>Hệ điều hành: Windows 7 SP1, Windows 8/8.1 (chỉ hỗ trợ 64bit)<br>CPU: Intel Core i5-750 @ 2.6 GHz hoặc AMD Phenom II X4 955 @ 3.2 GHz<br>RAM: 4GB<br>Video card: Hỗ trợ DirectX 11 với 1GB VRAM (NVIDIA GeForce GTX 460 hoặc AMD Radeon HD5850<br>HDD: 10 GB<br>Card âm thanh: 100% DirectX 10 compatible","./img/content/fo4/fo4-1.jpg","./img/content/fo4/fo4-2.jpg");
sp[17] = new sanpham("17","NV PL TGM","The Elder Scrolls V: Skyrim Special Edition","900.000","./img/content/tesv/tesv-0.jpg","<b>Mã sản phẩm:</b> tesv-17<br><b>Tình trạng:</b> <span style='color:#27CF2D;'>Còn hàng</span><br><b>Giá:</b> <span style='color:#27CF2D;'>900.000 VNĐ</span><br><br><br><b>GIỚI THIỆU VỀ GAME:</b></br></br>Cốt truyện của Skyrim xoay quanh hành trình nhân vật của người chơi đánh bại Alduin, một con rồng được tiên đoán là sẽ hủy diệt thế giới. Xảy ra 200 năm sau Oblivion, trò chơi lấy bối cảnh tại tỉnh Skyrim hư cấu nằm trên lục địa Tamriel của hành tinh Nirn. Lối chơi thế giới mở của loạt trò chơi The Elder Scrolls tiếp tục trở lại ở Skyrim; người chơi có thể bỏ qua hoặc trì hoãn cốt truyện để tự do khám phá. Skyrim đã đạt được thành công về mặt thương mại với 7 triệu bản được bán ra trong tuần đầu tiên.<br><br><br><b>CẤU HÌNH TỐI THIỂU:</b></br></br>Hệ điều hành: Windows 7 SP1, Windows 8/8.1 (chỉ hỗ trợ 64bit)<br>CPU: Intel Core i5-750 @ 2.6 GHz hoặc AMD Phenom II X4 955 @ 3.2 GHz<br>RAM: 4GB<br>Video card: Hỗ trợ DirectX 11 với 1GB VRAM (NVIDIA GeForce GTX 460 hoặc AMD Radeon HD5850<br>HDD: 10 GB<br>Card âm thanh: 100% DirectX 10 compatible","./img/content/tesv/tesv-3.jpg","./img/content/tesv/tesv-2.jpg");
sp[18] = new sanpham("18","NV PL TGM KD FPS","Dying Light Enhanced Edition","549.000","./img/content/dl/dl-0.jpg","<b>Mã sản phẩm:</b> dl-18<br><b>Tình trạng:</b> <span style='color:#27CF2D;'>Còn hàng</span><br><b>Giá:</b> <span style='color:#27CF2D;'>549.000 VNĐ</span><br><br><br><b>GIỚI THIỆU VỀ GAME:</b></br></br> Dying Light là những game mà những người yêu thích “SĂN ZOMBIE”. Với vai trò là 1 parkour runner, bạn sẽ được trải nghiệm những tình tiết kịch tính, Nhận tiếp tế hoặc chế tạo vũ khí để đánh bại lại những Zombies đang đói.<br><br><br><b>CẤU HÌNH TỐI THIỂU:</b></br></br>Hệ điều hành: Windows 7 SP1, Windows 8/8.1 (chỉ hỗ trợ 64bit)<br>CPU: Intel Core i5-750 @ 2.6 GHz hoặc AMD Phenom II X4 955 @ 3.2 GHz<br>RAM: 4GB<br>Video card: Hỗ trợ DirectX 11 với 1GB VRAM (NVIDIA GeForce GTX 460 hoặc AMD Radeon HD5850<br>HDD: 10 GB<br>Card âm thanh: 100% DirectX 10 compatible","./img/content/dl/dl-1.jpg","./img/content/dl/dl-2.jpg");
sp[19] = new sanpham("19","NV KD","RESIDENT EVIL 7 biohazard / BIOHAZARD 7 resident evil","398.000","./img/content/re7/re7-0.jpg","<b>Mã sản phẩm:</b> re7-19<br><b>Tình trạng:</b> <span style='color:#27CF2D;'>Còn hàng</span><br><b>Giá:</b> <span style='color:#27CF2D;'>398.000 VNĐ</span><br><br><br><b>GIỚI THIỆU VỀ GAME:</b></br></br>Diễn biến cốt truyện diễn ra sau Resident Evil 6, khi dịch bệnh đến từ C-virus từng lây lan nhanh như cháy rừng và đe dọa phá hủy thế giới, đã dần được kiểm soát. Vẫn còn đó sự sợ hãi, nhưng thế giới đang dần trở lại bình yên. Tuy nhiên, những điều lạ lùng lại đang xảy ra xung quanh thị trấn nhỏ Dulvey, bang Louisiana, và mọi thứ đang bị khuấy động trở lại. Nhưng không một ai biết thực hư ra sao, và họ cũng không dám dấn thân quá sâu để tìm kiếm sự thật, trừ một anh chàng muốn truy tìm tung tích người vợ yêu quý của mình.<br><br><br><b>CẤU HÌNH TỐI THIỂU:</b></br></br>Hệ điều hành: Windows 7 SP1, Windows 8/8.1 (chỉ hỗ trợ 64bit)<br>CPU: Intel Core i5-750 @ 2.6 GHz hoặc AMD Phenom II X4 955 @ 3.2 GHz<br>RAM: 4GB<br>Video card: Hỗ trợ DirectX 11 với 1GB VRAM (NVIDIA GeForce GTX 460 hoặc AMD Radeon HD5850<br>HDD: 10 GB<br>Card âm thanh: 100% DirectX 10 compatible","./img/content/re7/re7-1.jpg","./img/content/re7/re7-3.jpg");
sp[20] = new sanpham("20","TT","NBA 2K19","984.000","./img/content/nba19/nba19-0.jpg","<b>Mã sản phẩm:</b> nba19-20<br><b>Tình trạng:</b> <span style='color:#27CF2D;'>Còn hàng</span><br><b>Giá:</b> <span style='color:#27CF2D;'>984.000 VNĐ</span><br><br><br><b>GIỚI THIỆU VỀ GAME:</b></br></br>Giống như những người tiền nhiệm, NBA 2K19 PC được phát triển dựa trên giải thi đấu bóng rổ nhà nghề Mỹ. Game tái hiện những trận đấu bóng rổ sôi động và chân thực. Người chơi sẽ có cảm giác như mình đang ở trên sân đấu, cầm bóng, di chuyển khéo léo để ném bóng vào lưới. Bàn thắng đẹp giúp bạn và đồng đội có những phút giây thăng hoa thật sự trên sàn đấu.<br><br><br><b>CẤU HÌNH TỐI THIỂU:</b></br></br>Hệ điều hành: Windows 7 SP1, Windows 8/8.1 (chỉ hỗ trợ 64bit)<br>CPU: Intel Core i5-750 @ 2.6 GHz hoặc AMD Phenom II X4 955 @ 3.2 GHz<br>RAM: 4GB<br>Video card: Hỗ trợ DirectX 11 với 1GB VRAM (NVIDIA GeForce GTX 460 hoặc AMD Radeon HD5850<br>HDD: 10 GB<br>Card âm thanh: 100% DirectX 10 compatible","./img/content/nba19/nba19-1.jpg","./img/content/nba19/nba19-2.jpg");
sp[21] = new sanpham("21","NV PL TGM","Assassin's Creed® Odyssey","990.000","./img/content/aco/aco-0.jpg","<b>Mã sản phẩm:</b> aco-21<br><b>Tình trạng:</b> <span style='color:#27CF2D;'>Còn hàng</span><br><b>Giá:</b> <span style='color:#27CF2D;'>990.000 VNĐ</span><br><br><br><b>GIỚI THIỆU VỀ GAME:</b></br></br>Với Odyssey, người chơi sẽ kiểm soát vận mệnh và viết nên cuộc phiêu lưu hoành tráng của riêng mình trong cuộc hành trình thành một anh hùng Spartan huyền thoại. Ubisoft hứa hẹn sẽ cho phép game thủ trải nghiệm những cuộc phiêu lưu đáng kinh ngạc trong một thế giới mà mọi sự lựa chọn đều quan trọng. Bị chối bỏ bởi chính gia đình, nhân vật chính sẽ phải đi từ lính đánh thuê lạc lõng, từng bước khẳng định vị thế trong xã hỗi và cuối cùng trở thành anh hùng Spartan huyền thoại để khám phá sự thật về quá khứ.<br><br><br><b>CẤU HÌNH TỐI THIỂU:</b></br></br>Hệ điều hành: Windows 7 SP1, Windows 8/8.1 (chỉ hỗ trợ 64bit)<br>CPU: Intel Core i5-750 @ 2.6 GHz hoặc AMD Phenom II X4 955 @ 3.2 GHz<br>RAM: 4GB<br>Video card: Hỗ trợ DirectX 11 với 1GB VRAM (NVIDIA GeForce GTX 460 hoặc AMD Radeon HD5850<br>HDD: 10 GB<br>Card âm thanh: 100% DirectX 10 compatible","./img/content/aco/aco-1.jpg","./img/content/aco/aco-2.jpg");
sp[22] = new sanpham("22","HD NV","HITMAN™ 2","990.000","./img/content/hm2/hm2-0.jpg","<b>Mã sản phẩm:</b> hm2-22<br><b>Tình trạng:</b> <span style='color:#27CF2D;'>Còn hàng</span><br><b>Giá:</b> <span style='color:#27CF2D;'>990.000 VNĐ</span><br><br><br><b>GIỚI THIỆU VỀ GAME:</b></br></br>Trong Hitman 2, game thủ sẽ có mặt trên khắp thế giới, theo dõi các mục tiêu của mình , thoải mái hoạt động trong một môi trường mở rộng lớn. Từ những con đường ướt đẫm nước mưa đến những khu rừng nhiệt đới tối tăm và nguy hiểm, không nơi nào là an toàn khi sát thủ sáng tạo nhất thế giới, Đặc vụ 47 chính thức ra tay.<br><br><br><b>CẤU HÌNH TỐI THIỂU:</b></br></br>Hệ điều hành: Windows 7 SP1, Windows 8/8.1 (chỉ hỗ trợ 64bit)<br>CPU: Intel Core i5-750 @ 2.6 GHz hoặc AMD Phenom II X4 955 @ 3.2 GHz<br>RAM: 4GB<br>Video card: Hỗ trợ DirectX 11 với 1GB VRAM (NVIDIA GeForce GTX 460 hoặc AMD Radeon HD5850<br>HDD: 10 GB<br>Card âm thanh: 100% DirectX 10 compatible","./img/content/hm2/hm3-4.jpg","./img/content/hm2/hm2-2.jpg");
sp[23] = new sanpham("23","HD NV FPS","Battlefield V","1.350.000","./img/content/bf5/bf5-0.jpg","<b>Mã sản phẩm:</b> bf5-0<br><b>Tình trạng:</b> <span style='color:#27CF2D;'>Còn hàng</span><br><b>Giá:</b> <span style='color:#27CF2D;'>1.350.000 VNĐ</span><br><br><br><b>GIỚI THIỆU VỀ GAME:</b></br></br>Battlefield V là thành viên mới nhất của dòng game cùng tên nổi tiếng cùng tên của hãng EA. Trò chơi được giới thiệu lần đầu tại sự kiện EA’s Play, diễn ra ngay trước thềm E3 2018. Battlefield V sẽ lấy bối cảnh về Đệ Nhị Thế Chiến (World War II), cuộc chiến được cho là tàn khốc và tốn kém nhất lịch sử nhân loại. Bạn sẽ được chứng kiến sự kinh hoàng của chiến tranh qua đôi mắt của những người đàn ông và phụ nữ trong Thế chiến thứ 2.<br><br><br><b>CẤU HÌNH TỐI THIỂU:</b></br></br>Hệ điều hành: Windows 7 SP1, Windows 8/8.1 (chỉ hỗ trợ 64bit)<br>CPU: Intel Core i5-750 @ 2.6 GHz hoặc AMD Phenom II X4 955 @ 3.2 GHz<br>RAM: 4GB<br>Video card: Hỗ trợ DirectX 11 với 1GB VRAM (NVIDIA GeForce GTX 460 hoặc AMD Radeon HD5850<br>HDD: 10 GB<br>Card âm thanh: 100% DirectX 10 compatible","./img/content/bf5/bf5-1.jpg","./img/content/bf5/bf5-2.jpg");
sp[24] = new sanpham("24","PL NV TGM","Darksiders III","620.000","./img/content/ds3/ds3-0.jpg","<b>Mã sản phẩm:</b> ds3-24<br><b>Tình trạng:</b> <span style='color:#27CF2D;'>Còn hàng</span><br><b>Giá:</b> <span style='color:#27CF2D;'>620.000 VNĐ</span><br><br><br><b>GIỚI THIỆU VỀ GAME:</b></br></br>Quay trở lại một trái đất khải huyền trong Darksiders III, một cuộc phiêu lưu hành động hack-n-slash, nơi người chơi đảm nhận vai trò của FURY trong nhiệm vụ săn lùng và xử lý Bảy tội lỗi chết người. Điều không thể đoán trước và bí ẩn nhất của Four Horsemen, FURY phải thành công khi nhiều người thất bại - để mang lại sự cân bằng cho các lực lượng hiện đang tàn phá Trái đất. Darksiders III là chương thứ ba được mong đợi từ lâu trong thương hiệu Darksiders được đánh giá cao.<br><br><br><b>CẤU HÌNH TỐI THIỂU:</b></br></br>Hệ điều hành: Windows 7 SP1, Windows 8/8.1 (chỉ hỗ trợ 64bit)<br>CPU: Intel Core i5-750 @ 2.6 GHz hoặc AMD Phenom II X4 955 @ 3.2 GHz<br>RAM: 4GB<br>Video card: Hỗ trợ DirectX 11 với 1GB VRAM (NVIDIA GeForce GTX 460 hoặc AMD Radeon HD5850<br>HDD: 10 GB<br>Card âm thanh: 100% DirectX 10 compatible","./img/content/ds3/ds3-1.jpg","./img/content/ds3/ds3-2.jpg");
sp[25] = new sanpham("25","PL NV TGM","Just Cause 4","1.291.500","./img/content/jc4/jc4-0.jpg","<b>Mã sản phẩm:</b> jc4-25<br><b>Tình trạng:</b> <span style='color:#27CF2D;'>Còn hàng</span><br><b>Giá:</b> <span style='color:#27CF2D;'>1.291.000 VNĐ</span><br><br><br><b>GIỚI THIỆU VỀ GAME:</b></br></br>Đến Just Cause 4, người chơi sẽ được chu du đến thế giới Nam Mỹ khổng lồ tràn đầy những xung đột, áp bức và những điều kiện thời tiết khắc nghiệt được gọi là Solis. Ở đây, nhân vật chính Rico sẽ phải đối mặt với những mối hiểm họa bằng vũ lực với đủ các loại khí tài quân sự từ thô sơ tới hiện đại. Dự kiến, Just Cause 4 sẽ phát hành vào ngày 4 tháng 12 tới đây trên PS4, Xbox One và PC.<br><br><br><b>CẤU HÌNH TỐI THIỂU:</b></br></br>Hệ điều hành: Windows 7 SP1, Windows 8/8.1 (chỉ hỗ trợ 64bit)<br>CPU: Intel Core i5-750 @ 2.6 GHz hoặc AMD Phenom II X4 955 @ 3.2 GHz<br>RAM: 4GB<br>Video card: Hỗ trợ DirectX 11 với 1GB VRAM (NVIDIA GeForce GTX 460 hoặc AMD Radeon HD5850<br>HDD: 10 GB<br>Card âm thanh: 100% DirectX 10 compatible","./img/content/jc4/jc4-1.jpg","./img/content/jc4/jc4-2.jpg");
sp[26] = new sanpham("26","ST CT KD","Dead by Daylight","188.000","./img/content/dbd/dbd-0.jpg","<b>Mã sản phẩm:</b> dbd-26<br><b>Tình trạng:</b> <span style='color:#27CF2D;'>Còn hàng</span><br><b>Giá:</b> <span style='color:#27CF2D;'>188.000 VNĐ</span><br><br><br><b>GIỚI THIỆU VỀ GAME:</b></br></br>Dead by Daylight là trò chơi kinh dị nhiều người chơi (5 người với thể thức 4 vs 1). Trong đó một người chơi nhập vai làm Killer; bốn người khác vào vai những Survivors, họ cố gắng trốn khỏi Killer bằng mọi cách để tránh bị bắt, tra tấn và giết. Những Survivors tham gia cuộc sinh tồn dưới góc quay người thứ ba, cho nên họ có nhận thức tình huống tốt hơn. Và thực ra suy cho cùng ai cũng mong muốn làm người sống xót bởi vì nó rất là ngầu. Có một điều cần quan tâm ở đây là mặc dù có lợi thế quan sát nhưng môi trường, không gian lại thay đổi liên tục theo mỗi game đấu.<br><br><br><b>CẤU HÌNH TỐI THIỂU:</b></br></br>Hệ điều hành: Windows 7 SP1, Windows 8/8.1 (chỉ hỗ trợ 64bit)<br>CPU: Intel Core i5-750 @ 2.6 GHz hoặc AMD Phenom II X4 955 @ 3.2 GHz<br>RAM: 4GB<br>Video card: Hỗ trợ DirectX 11 với 1GB VRAM (NVIDIA GeForce GTX 460 hoặc AMD Radeon HD5850<br>HDD: 10 GB<br>Card âm thanh: 100% DirectX 10 compatible","./img/content/dbd/dbd-1.jpg","./img/content/dbd/dbd-2.jpg");
sp[27] = new sanpham("27","ID KD","Visage","220.000","./img/content/vsg/vsg-0.jpg","<b>Mã sản phẩm:</b> vsg-27<br><b>Tình trạng:</b> <span style='color:#27CF2D;'>Còn hàng</span><br><b>Giá:</b> <span style='color:#27CF2D;'>220.000 VNĐ</span><br><br><br><b>GIỚI THIỆU VỀ GAME:</b></br></br>Trò chơi được đặt bên trong một ngôi nhà lớn trong đó những điều khủng khiếp đã xảy ra. Bạn sẽ đi lang thang qua hành lang ảm đạm, khám phá mọi phòng chết, và bị lạc trong những mê cung bất tận, đầu bạn lấp đầy những kỷ niệm về những gia đình đã từng sống trong ngôi nhà này. Môi trường xoắn này, khoảng trống của bất kỳ cuộc sống nào khác ngoài cuộc sống của bạn, đưa bạn đến những nơi bạn thậm chí không thể tưởng tượng nổi.<br><br><br><b>CẤU HÌNH TỐI THIỂU:</b></br></br>Hệ điều hành: Windows 7 SP1, Windows 8/8.1 (chỉ hỗ trợ 64bit)<br>CPU: Intel Core i5-750 @ 2.6 GHz hoặc AMD Phenom II X4 955 @ 3.2 GHz<br>RAM: 4GB<br>Video card: Hỗ trợ DirectX 11 với 1GB VRAM (NVIDIA GeForce GTX 460 hoặc AMD Radeon HD5850<br>HDD: 10 GB<br>Card âm thanh: 100% DirectX 10 compatible","./img/content/vsg/vsg-1.jpg","./img/content/vsg/vsg-2.jpg");
sp[28] = new sanpham("28","ST FPS KD","Left 4 Dead 2","120.000","./img/content/l4d2/l4d2-0.jpg","<b>Mã sản phẩm:</b> l4d2-28<br><b>Tình trạng:</b> <span style='color:#27CF2D;'>Còn hàng</span><br><b>Giá:</b> <span style='color:#27CF2D;'>120.000 VNĐ</span><br><br><br><b>GIỚI THIỆU VỀ GAME:</b></br></br>Được viện tương tác và khoa học (AISA) của Mỹ, và nhiều trang tin điện tử uy tín của Mỹ như ISN, Gametv đánh giá là game chơi mạng suất xắc nhất năm 2008 với nhiều giải thưởng lớn đạt được doanh số bán ra ấn tượng giúp cho Left 4 Dead 1 trở con gà đẻ trứng gà mới của Valve bên cạnh Half Life, Counter Strike, Team Fortress vốn đã khá quen thuộc với nhiều game thủ. Không bỏ qua cơ hội khai thác thương hiệu đang hút khách này, hãng valve tiếp tục cho ra mắt phiên bản thứ hai của tựa game này, Left 4 Dead 2.<br><br><br><b>CẤU HÌNH TỐI THIỂU:</b></br></br>Hệ điều hành: Windows 7 SP1, Windows 8/8.1 (chỉ hỗ trợ 64bit)<br>CPU: Intel Core i5-750 @ 2.6 GHz hoặc AMD Phenom II X4 955 @ 3.2 GHz<br>RAM: 4GB<br>Video card: Hỗ trợ DirectX 11 với 1GB VRAM (NVIDIA GeForce GTX 460 hoặc AMD Radeon HD5850<br>HDD: 10 GB<br>Card âm thanh: 100% DirectX 10 compatible","./img/content/l4d2/l4d2-1.jpg","./img/content/l4d2/l4d2-2.jpg");
sp[29] = new sanpham("29","ST PL VT","Subnautica","220.000","./img/content/sn/sn-0.jpg","<b>Mã sản phẩm:</b> sn-29<br><b>Tình trạng:</b> <span style='color:#27CF2D;'>Còn hàng</span><br><b>Giá:</b> <span style='color:#27CF2D;'>220.000 VNĐ</span><br><br><br><b>GIỚI THIỆU VỀ GAME:</b></br></br>Subnautica là một trò chơi phiêu lưu, khám phá, thế giới mở ở dưới nước được đặt trên một hành tinh đại dương ngoài hành tinh. Một thế giới rộng mở, tự do và nguy hiểm đang chờ đón bạn!<br><br><br><b>CẤU HÌNH TỐI THIỂU:</b></br></br>Hệ điều hành: Windows 7 SP1, Windows 8/8.1 (chỉ hỗ trợ 64bit)<br>CPU: Intel Core i5-750 @ 2.6 GHz hoặc AMD Phenom II X4 955 @ 3.2 GHz<br>RAM: 4GB<br>Video card: Hỗ trợ DirectX 11 với 1GB VRAM (NVIDIA GeForce GTX 460 hoặc AMD Radeon HD5850<br>HDD: 10 GB<br>Card âm thanh: 100% DirectX 10 compatible","./img/content/sn/sn-1.jpg","./img/content/sn/sn-2.jpg");
sp[30] = new sanpham("30","ST PL VT","ASTRONEER","280.000","./img/content/ast/ast-0.jpg","<b>Mã sản phẩm:</b> ast-30<br><b>Tình trạng:</b> <span style='color:#27CF2D;'>Còn hàng</span><br><b>Giá:</b> <span style='color:#27CF2D;'>280.000 VNĐ</span><br><br><br><b>GIỚI THIỆU VỀ GAME:</b></br></br>Astroneer là tựa game thám hiểm vũ trụ với một chút gia vị sinh tồn được kết hợp tài tình sẽ là lựa chọn hoàn hảo cho bạn vào cuối tuần này. Trong game, bạn có thể tự mình khám phá vũ trụ rộng lớn hoặc co-op cùng với bạn bè của mình trong chế độ online của game. Khởi đầu trò chơi, bạn sẽ thấy mình trên một phi thuyền không gian, chỉ túi đựng đồ cùng một ít công cụ bạn để bạn bắt đầu khám phá hành tinh này,  bạn sẽ tìm kiếm các nguồn tài nguyên, các nguyên vật liệu để xây dựng lên căn cứ và khám phá các công nghệ mới. Astroneer cho phép bạn chỉnh sửa lại không gian xung quanh bạn.<br><br><br><b>CẤU HÌNH TỐI THIỂU:</b></br></br>Hệ điều hành: Windows 7 SP1, Windows 8/8.1 (chỉ hỗ trợ 64bit)<br>CPU: Intel Core i5-750 @ 2.6 GHz hoặc AMD Phenom II X4 955 @ 3.2 GHz<br>RAM: 4GB<br>Video card: Hỗ trợ DirectX 11 với 1GB VRAM (NVIDIA GeForce GTX 460 hoặc AMD Radeon HD5850<br>HDD: 10 GB<br>Card âm thanh: 100% DirectX 10 compatible","./img/content/ast/ast-1.jpg","./img/content/ast/ast-2.jpg");
sp[31] = new sanpham("31","VT GL","Jurassic World Evolution","1.252.000","./img/content/jwe/jwe-0.jpg","<b>Mã sản phẩm:</b> jwe-31<br><b>Tình trạng:</b> <span style='color:#27CF2D;'>Còn hàng</span><br><b>Giá:</b> <span style='color:#27CF2D;'>252.000 VNĐ</span><br><br><br><b>GIỚI THIỆU VỀ GAME:</b></br></br>Kiểm soát bức tranh lớn với các công cụ quản lý sâu hoặc thực hành để đối mặt với những thách thức trên mặt đất hoặc trong không khí. Mở rộng hòn đảo của bạn và chọn hành trình của riêng bạn trong một câu chuyện hoàn toàn mới với các nhân vật mang tính biểu tượng từ khắp nơi trên thương hiệu và hàng thập kỷ của truyền thuyết Jurassic trong tầm tay bạn.<br><br><br><b>CẤU HÌNH TỐI THIỂU:</b></br></br>Hệ điều hành: Windows 7 SP1, Windows 8/8.1 (chỉ hỗ trợ 64bit)<br>CPU: Intel Core i5-750 @ 2.6 GHz hoặc AMD Phenom II X4 955 @ 3.2 GHz<br>RAM: 4GB<br>Video card: Hỗ trợ DirectX 11 với 1GB VRAM (NVIDIA GeForce GTX 460 hoặc AMD Radeon HD5850<br>HDD: 10 GB<br>Card âm thanh: 100% DirectX 10 compatible","./img/content/jwe/jwe-1.jpg","./img/content/jwe/jwe-2.jpg");
sp[32] = new sanpham("32","FPS VT","Portal 2","120.000","./img/content/pt2/pt2-0.jpg","<b>Mã sản phẩm:</b> pt2-32<br><b>Tình trạng:</b> <span style='color:#27CF2D;'>Còn hàng</span><br><b>Giá:</b> <span style='color:#27CF2D;'>120.000 VNĐ</span><br><br><br><b>GIỚI THIỆU VỀ GAME:</b></br></br>Portal 2 được tạo ra từ công thức từng đoạt giải thưởng về lối chơi, câu chuyện và âm nhạc sáng tạo đã giành được The Original Portal với hơn 70 giải thưởng trong ngành và tạo ra một thể loại mới.<br><br><br><b>CẤU HÌNH TỐI THIỂU:</b></br></br>Hệ điều hành: Windows 7 SP1, Windows 8/8.1 (chỉ hỗ trợ 64bit)<br>CPU: Intel Core i5-750 @ 2.6 GHz hoặc AMD Phenom II X4 955 @ 3.2 GHz<br>RAM: 4GB<br>Video card: Hỗ trợ DirectX 11 với 1GB VRAM (NVIDIA GeForce GTX 460 hoặc AMD Radeon HD5850<br>HDD: 10 GB<br>Card âm thanh: 100% DirectX 10 compatible","./img/content/pt2/pt2-1.jpg","./img/content/pt2/pt2-2.jpg");
sp[33] = new sanpham("33","PL NV TGM","FINAL FANTASY XV WINDOWS EDITION","1.135.000","./img/content/ffxv/ffxv-0.jpg","<b>Mã sản phẩm:</b> ffxv-33<br><b>Tình trạng:</b> <span style='color:#27CF2D;'>Còn hàng</span><br><b>Giá:</b> <span style='color:#27CF2D;'>1.135.000 VNĐ</span><br><br><br><b>GIỚI THIỆU VỀ GAME:</b></br></br>Là một fan hâm mộ dòng game Final Fantasy, chắc chắn, các bạn sẽ cảm thấy tuyệt đối hài lòng với Final Fantasy XV - Một trong những tựa game hay nhất từ trước đến nay trong cả series.<br><br><br><b>CẤU HÌNH TỐI THIỂU:</b></br></br>Hệ điều hành: Windows 7 SP1, Windows 8/8.1 (chỉ hỗ trợ 64bit)<br>CPU: Intel Core i5-750 @ 2.6 GHz hoặc AMD Phenom II X4 955 @ 3.2 GHz<br>RAM: 4GB<br>Video card: Hỗ trợ DirectX 11 với 1GB VRAM (NVIDIA GeForce GTX 460 hoặc AMD Radeon HD5850<br>HDD: 10 GB<br>Card âm thanh: 100% DirectX 10 compatible","./img/content/ffxv/ffxv-1.jpg","./img/content/ffxv/ffxv-2.jpg");
sp[34] = new sanpham("34","PL VT","X4: Foundations","440.000","./img/content/x4f/x4f-0.jpg","<b>Mã sản phẩm:</b> x4f-34<br><b>Tình trạng:</b> <span style='color:#27CF2D;'>Còn hàng</span><br><b>Giá:</b> <span style='color:#27CF2D;'>440.000 VNĐ</span><br><br><br><b>GIỚI THIỆU VỀ GAME:</b></br></br>X4 sẽ cho phép bạn bay tất cả các tàu cá nhân. Từ các trinh sát nhỏ trên một loạt các lớp tàu lên đến tàu sân bay lớn nhất, mọi thứ đều có thể được lái từ buồng lái hoặc tầm nhìn bên ngoài. Một trọng tâm lớn trong sự phát triển của X4 là để đạt được một trải nghiệm liền mạch và nhập vai khi di chuyển giữa các tàu. Bạn có thể rời khỏi tàu, leo xuống một cái thang, đi bộ qua bến tàu của một trạm không gian rộng lớn vào một con tàu khác mà bạn có thể đậu ở đó và thay thế phi công đang làm việc cho bạn chỉ bằng cách nhấp vào ghế của mình.<br><br><br><b>CẤU HÌNH TỐI THIỂU:</b></br></br>Hệ điều hành: Windows 7 SP1, Windows 8/8.1 (chỉ hỗ trợ 64bit)<br>CPU: Intel Core i5-750 @ 2.6 GHz hoặc AMD Phenom II X4 955 @ 3.2 GHz<br>RAM: 4GB<br>Video card: Hỗ trợ DirectX 11 với 1GB VRAM (NVIDIA GeForce GTX 460 hoặc AMD Radeon HD5850<br>HDD: 10 GB<br>Card âm thanh: 100% DirectX 10 compatible","./img/content/x4f/x4f-1.jpg","./img/content/x4f/x4f-2.jpg");
sp[35] = new sanpham("35","CT","Artifact","470.000","./img/content/atf/atf-0.jpg","<b>Mã sản phẩm:</b> atf-35<br><b>Tình trạng:</b> <span style='color:#27CF2D;'>Còn hàng</span><br><b>Giá:</b> <span style='color:#27CF2D;'>470.000 VNĐ</span><br><br><br><b>GIỚI THIỆU VỀ GAME:</b></br></br>Sự hợp tác giữa nhà thiết kế trò chơi thẻ huyền thoại Richard Garfield và Valve, Artifact là một trò chơi thẻ kỹ thuật số kết hợp giữa trò chơi chiến lược và cạnh tranh sâu sắc với thiết lập phong phú của DotA 2. Kết quả là một trò chơi giao dịch tuyệt vời và trực quan không giống bất kỳ trò chơi nào khác.<br><br><br><b>CẤU HÌNH TỐI THIỂU:</b></br></br>Hệ điều hành: Windows 7 SP1, Windows 8/8.1 (chỉ hỗ trợ 64bit)<br>CPU: Intel Core i5-750 @ 2.6 GHz hoặc AMD Phenom II X4 955 @ 3.2 GHz<br>RAM: 4GB<br>Video card: Hỗ trợ DirectX 11 với 1GB VRAM (NVIDIA GeForce GTX 460 hoặc AMD Radeon HD5850<br>HDD: 10 GB<br>Card âm thanh: 100% DirectX 10 compatible","./img/content/atf/atf-1.jpg","./img/content/atf/atf-2.jpg");
sp[36] = new sanpham("36","","Steam Wallet Code 2$","49.000","./img/card/card2.jpg","","","");
sp[37] = new sanpham("37","","Steam Wallet Code 5$","122.000","./img/card/card5.jpg","","","");
sp[38] = new sanpham("38","","Steam Wallet Code 10$","240.000","./img/card/card10.jpg","","","");
sp[39] = new sanpham("39","","Steam Wallet Code 20$","480.000","./img/card/card20.jpg","","","");
sp[40] = new sanpham("40","","Steam Wallet Code 50$","1.220.000","./img/card/card50.jpg","","","");
sp[41] = new sanpham("41","","Steam Wallet Code 100$","2.300.000","./img/card/card100.jpg","","","");
function Card(masp,ten,gia,hinh)
{
	this.masp=masp;
	this.ten=ten;
	this.gia=gia;
	this.hinh=hinh;
}

var card = new Array();

function View(ma,ten)
{
	this.ma=ma;
	this.ten=ten;
}
var view = new Array();
view[0] = new View("QLTK", "Quản lý tài khoản");
view[1] = new View("DH", "Đơn hàng");
view[2] = new View("DSSP", "Danh sách sản phẩm");

function Thongtin(hoten,mssv,congviec)
{
	this.hoten=hoten;
	this.mssv=mssv;
	this.congviec=congviec;
}
var tt = new Array();
tt[0] = new Thongtin("Ngô Chí Trung","3117410277","Javascript(Hiển thị SP, Chi tiết SP, Thông tin, Tìm kiếm, Giỏ hàng), Trang admin(70%)");
tt[1] = new Thongtin("Hà Thiện Tuấn","3117410285","Javascript(Danh mục, Kiểm tra ĐN-ĐK, localStorage, Giỏ hàng), Giao diện hoàn thiện(index-ĐN-ĐK), Slideshow, Trang admin(30%)");
tt[2] = new Thongtin("Vũ Minh Thế","3117410245","Giao diện sơ khai(index-ĐN-ĐK), Banner, Logo, Footer, Chi tiết SP, Giỏ hàng(Giao diện)");
tt[3] = new Thongtin("Trần Thanh Toàn","3117410265","Footer, Chi tiết SP, Giở hàng(Giao diện)");

